In [1]:
import requests
import pandas as pd
import json
from pprint import pprint

In [2]:
base_url = 'https://fantasy.premierleague.com/api/'

In [31]:
def get_json_data(endpoint: str):
    response = requests.get(base_url+endpoint)
    print(response)
    return response.json()

In [32]:
data = get_json_data('bootstrap-static')
pprint(data, indent=2)

<Response [200]>
{ 'chips': [ { 'chip_type': 'transfer',
               'id': 1,
               'name': 'wildcard',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 2,
               'stop_event': 19},
             { 'chip_type': 'transfer',
               'id': 2,
               'name': 'wildcard',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38},
             { 'chip_type': 'transfer',
               'id': 3,
               'name': 'freehit',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 2,
               'stop_event': 19},
             { 'chip_type': 'team',
               'id': 4,
               'name': 'bboost',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 1,
               'stop_event': 19},
             { 'chip_type': 'team',
               'id': 5,
               'name': '3xc',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 1,
               'stop_event': 19},
             { 'chip_type': 'transfer',
               'id': 6,
               'name': 'freehit',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38},
             { 'chip_type': 'team',
               'id': 7,
               'name': 'bboost',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38},
             { 'chip_type': 'team',
               'id': 8,
               'name': '3xc',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38}],
  'element_stats': [ {'label': 'Minutes played', 'name': 'minutes'},
                     {'label': 'Goals scored', 'name': 'goals_scored'},
                     {'label': 'Assists', 'name': 'assists'},
                     {'label': 'Clean sheets', 'name': 'clean_sheets'},
                     {'label': 'Goals conceded', 'name': 'goals_conceded'},
                     {'label': 'Own goals', 'name': 'own_goals'},
                     {'label': 'Penalties saved', 'name': 'penalties_saved'},
                     {'label': 'Penalties missed', 'name': 'penalties_missed'},
                     {'label': 'Yellow cards', 'name': 'yellow_cards'},
                     {'label': 'Red cards', 'name': 'red_cards'},
                     {'label': 'Saves', 'name': 'saves'},
                     {'label': 'Bonus', 'name': 'bonus'},
                     {'label': 'Bonus Points System', 'name': 'bps'},
                     {'label': 'Influence', 'name': 'influence'},
                     {'label': 'Creativity', 'name': 'creativity'},
                     {'label': 'Threat', 'name': 'threat'},
                     {'label': 'ICT Index', 'name': 'ict_index'},
                     { 'label': 'Clearances, blocks and interceptions',
                       'name': 'clearances_blocks_interceptions'},
                     {'label': 'Recoveries', 'name': 'recoveries'},
                     {'label': 'Tackles', 'name': 'tackles'},
                     { 'label': 'Defensive Contribution',
                       'name': 'defensive_contribution'},
                     {'label': 'Game(s) Started', 'name': 'starts'},
                     {'label': 'Expected Goals', 'name': 'expected_goals'},
                     {'label': 'Expected Assists', 'name': 'expected_assists'},
                     { 'label': 'Expected Goal Involvements',
                       'name': 'expected_goal_involvements'},
                     { 'label': 'Expected Goals Conceded',
                       'name': 'expected_goals_conceded'}],
  'element_types': [ { 'element_count': 95,
                       'id': 1,
                       'plural_name': 'Goalkeepers',
                       'plural_name_short': 'GKP',
                       'singular_name': 'Goalkeeper',
                       'singular_name_short': 'GKP',
                       'squad_max_play': 1,
                       'squad_max_select': None,
                       'squad_min_play': 1,
                       'squad_min_select': None,
                       'squad_select': 2,
                       'sub_positions_locked': [12],
                       'ui_shirt_specific': True},
                     { 'element_count': 268,
                       'id': 2,
                       'plural_name': 'Defenders',
                       'plural_name_short': 'DEF',
                       'singular_name': 'Defender',
                       'singular_name_short': 'DEF',
                       'squad_max_play': 5,
                       'squad_max_select': None,
                       'squad_min_play': 3,
                       'squad_min_select': None,
                       'squad_select': 5,
                       'sub_positions_locked': [],
                       'ui_shirt_specific': False},
                     { 'element_count': 370,
                       'id': 3,
                       'plural_name': 'Midfielders',
                       'plural_name_short': 'MID',
                       'singular_name': 'Midfielder',
                       'singular_name_short': 'MID',
                       'squad_max_play': 5,
                       'squad_max_select': None,
                       'squad_min_play': 2,
                       'squad_min_select': None,
                       'squad_select': 5,
                       'sub_positions_locked': [],
                       'ui_shirt_specific': False},
                     { 'element_count': 92,
                       'id': 4,
                       'plural_name': 'Forwards',
                       'plural_name_short': 'FWD',
                       'singular_name': 'Forward',
                       'singular_name_short': 'FWD',
                       'squad_max_play': 3,
                       'squad_max_select': None,
                       'squad_min_play': 1,
                       'squad_min_select': None,
                       'squad_select': 3,
                       'sub_positions_locked': [],
                       'ui_shirt_specific': False}],
  'elements': [ { 'assists': 0,
                  'birth_date': '1995-09-15',
                  'bonus': 6,
                  'bps': 515,
                  'can_select': True,
                  'can_transact': True,
                  'chance_of_playing_next_round': None,
                  'chance_of_playing_this_round': None,
                  'clean_sheets': 15,
                  'clean_sheets_per_90': 0.48,
                  'clearances_blocks_interceptions': 30,
                  'code': 154561,
                  'corners_and_indirect_freekicks_order': None,
                  'corners_and_indirect_freekicks_text': '',
                  'cost_change_event': 0,
                  'cost_change_event_fall': 0,
                  'cost_change_start': 5,
                  'cost_change_start_fall': -5,
                  'creativity': '33.4',
                  'creativity_rank': 376,
                  'creativity_rank_type': 3,
                  'defensive_contribution': 0,
                  'defensive_contribution_per_90': 0.0,
                  'direct_freekicks_order': None,
                  'direct_freekicks_text': '',
                  'dreamteam_count': 1,
                  'element_type': 1,
                  'ep_next': '6.7',
                  'ep_this': '0.0',
                  'event_points': 0,
                  'expected_assists': '0.06',
                  'expected_assists_per_90': 0.0,
                  'expected_goal_involvements': '0.06',
                  'expected_goal_involvements_per_90': 0.0,
                  'expected_goals': '0.00',
                  'expected_goals_conceded': '22.30',
                  'expected_goals_conceded_per_90': 0.72,
                  'expected_goals_per_90': 0.0,
                  'first_name': 'David',
                  'form': '5.7',
                  'form_rank': 23,
                  'form_rank_type': 1,
                  'goals_conceded': 22,
                  'goals_conceded_per_90': 0.71,
                  'goals_scored': 0,
                  'has_temporary_code': False,
                  'ict_index': '48.0',
                  'ict_index_rank': 270,
                  'ict_index_rank_type': 16,
                  'id': 1,
                  'in_dreamteam': True,
                  'influence': '445.8',
                  'influence_rank': 108,
                  'influence_rank_type': 18,
                  'known_name': '',
                  'minutes': 2790,
                  'news': '',
                  'news_added': None,
                  'now_cost': 60,
                  'now_cost_rank': 86,
                  'now_cost_rank_type': 1,
                  'opta_code': 'p154561',
                  'own_goals': 0,
                  'penalties_missed': 0,
                  'penalties_order': None,
                  'penalties_saved': 0,
                  'penalties_text': '',
                  'photo': '154561.jpg',
                  'points_per_game': '4.2',
                  'points_per_game_rank': 51,
                  'points_per_game_rank_type': 3,
                  'price_change_percent': '0',
                  'recoveries': 257,
                  'red_cards': 0,
                  'region': 200,
                  'removed': False,
                  'saves': 50,
                  'saves_per_90': 1.61,
                  'scout_news_link': '',
                  'scout_risks': [],
                  'second_name': 'Raya Martín',
                  'selected_by_percent': '34.6',
                  'selected_rank': 9,
                  'selected_rank_type': 1,
                  'special': False,
                  'squad_number': None,
                  'starts': 31,
                  'starts_per_90': 1.0,
                  'status': 'a',
                  'tackles': 1,
                  'team': 1,
                  'team_code': 3,
                  'team_join_date': '2024-07-04',
                  'threat': '0.0',
                  'threat_rank': 816,
                  'threat_rank_type': 95,
                  'total_points': 129,
                  'transfers_in': 4165152,
                  'transfers_in_event': 44475,
                  'transfers_out': 2476167,
                  'transfers_out_event': 8873,
                  'value_form': '1.0',
                  'value_season': '21.5',
                  'web_name': 'Raya',
                  'yellow_cards': 1},
                { 'assists': 0,
                  'birth_date': '1994-10-03',
                  'bonus': 0,
                  'bps': 0,
                  'can_select': True,
                  'can_transact': True,
                  'chance_of_playing_next_round': None,
                  'chance_of_playing_this_round': None,
                  'clean_sheets': 0,
                  'clean_sheets_per_90': 0,
                  'clearances_blocks_interceptions': 0,
                  'code': 109745,
                  'corners_and_indirect_freekicks_order': None,
                  'corners_and_indirect_freekicks_text': '',
                  'cost_change_event': 0,
                  'cost_change_event_fall': 0,
                  'cost_change_start': -5,
                  'cost_change_start_fall': 5,
                  'creativity': '0.0',
                  'creativity_rank': 559,
                  'creativity_rank_type': 51,
                  'defensive_contribution': 0,
                  'defensive_contribution_per_90': 0,
                  'direct_freekicks_order': None,
                  'direct_freekicks_text': '',
                  'dreamteam_count': 0,
                  'element_type': 1,
                  'ep_next': '1.0',
                  'ep_this': '0.0',
                  'event_points': 0,
                  'expected_assists': '0.00',
                  'expected_assists_per_90': 0,
                  'expected_goal_involvements': '0.00',
                  'expected_goal_involvements_per_90': 0,
                  'expected_goals': '0.00',
                  'expected_goals_conceded': '0.00',
                  'expected_goals_conceded_per_90': 0,
                  'expected_goals_per_90': 0,
                  'first_name': 'Kepa',
                  'form': '0.0',
                  'form_rank': 448,
                  'form_rank_type': 56,
                  'goals_conceded': 0,
                  'goals_conceded_per_90': 0,
                  'goals_scored': 0,
                  'has_temporary_code': False,
                  'ict_index': '0.0',
                  'ict_index_rank': 572,
                  'ict_index_rank_type': 66,
                  'id': 2,
                  'in_dreamteam': False,
                  'influence': '0.0',
                  'influence_rank': 570,
                  'influence_rank_type': 66,
                  'known_name': '',
                  'minutes': 0,
                  'news': '',
                  'news_added': None,
                  'now_cost': 40,
                  'now_cost_rank': 668,
                  'now_cost_rank_type': 43,
                  'opta_code': 'p109745',
                  'own_goals': 0,
                  'penalties_missed': 0,
                  'penalties_order': None,
                  'penalties_saved': 0,
                  'penalties_text': '',
                  'photo': '109745.jpg',
                  'points_per_game': '0.0',
                  'points_per_game_rank': 581,
                  'points_per_game_rank_type': 66,
                  'price_change_percent': '0',
                  'recoveries': 0,
                  'red_cards': 0,
                  'region': 200,
                  'removed': False,
                  'saves': 0,
                  'saves_per_90': 0,
                  'scout_news_link': '',
                  'scout_risks': [],
                  'second_name': 'Arrizabalaga Revuelta',
                  'selected_by_percent': '0.4',
                  'selected_rank': 285,
                  'selected_rank_type': 37,
                  'special': False,
                  'squad_number': None,
                  'starts': 0,
                  'starts_per_90': 0,
                  'status': 'a',
                  'tackles': 0,
                  'team': 1,
                  'team_code': 3,
                  'team_join_date': '2025-07-01',
                  'threat': '0.0',
                  'threat_rank': 529,
                  'threat_rank_type': 38,
                  'total_points': 0,
                  'transfers_in': 14869,
                  'transfers_in_event': 117,
                  'transfers_out': 77564,
                  'transfers_out_event': 155,
                  'value_form': '0.0',
                  'value_season': '0.0',
                  'web_name': 'Arrizabalaga',
                  'yellow_cards': 0},
                { 'assists': 0,
                  'birth_date': '2002-04-13',
                  'bonus': 0,
                  'bps': 0,
                  'can_select': False,
                  'can_transact': True,
                  'chance_of_playing_next_round': 0,
                  'chance_of_playing_this_round': 0,
                  'clean_sheets': 0,
                  'clean_sheets_per_90': 0,
                  'clearances_blocks_interceptions': 0,
                  'code': 463748,
                  'corners_and_indirect_freekicks_order': None,
                  'corners_and_indirect_freekicks_text': '',
                  'cost_change_event': 0,
                  'cost_change_event_fall': 0,
                  'cost_change_start': 0,
                  'cost_change_start_fall': 0,
                  'creativity': '0.0',
                  'creativity_rank': 578,
                  'creativity_rank_type': 62,
                  'defensive_contribution': 0,
                  'defensive_contribution_per_90': 0,
                  'direct_freekicks_order': None,
                  'direct_freekicks_text': '',
                  'dreamteam_count': 0,
                  'element_type': 1,
                  'ep_next': '0.0',
                  'ep_this': '0.0',
                  'event_points': 0,
                  'expected_assists': '0.00',
                  'expected_assists_per_90': 0,
                  'expected_goal_involvements': '0.00',
                  'expected_goal_involvements_per_90': 0,
                  'expected_goals': '0.00',
                  'expected_goals_conceded': '0.00',
                  'expected_goals_conceded_per_90': 0,
                  'expected_goals_per_90': 0,
                  'first_name': 'Karl',
                  'form': '0.0',
                  'form_rank': 466,
                  'form_rank_type': 66,
                  'goals_conceded': 0,
                  'goals_conceded_per_90': 0,
                  'goals_scored': 0,
                  'has_temporary_code': False,
                  'ict_index': '0.0',
                  'ict_index_rank': 589,
                  'ict_index_rank_type': 75,
                  'id': 3,
                  'in_dreamteam': False,
                  'influence': '0.0',
                  'influence_rank': 587,
                  'influence_rank_type': 75,
                  'known_name': '',
                  'minutes': 0,
                  'news': 'Has joined Werder Bremen on loan for the rest of '
                          'the season.',
                  'news_added': '2025-08-26T13:44:02.357864Z',
                  'now_cost': 40,
                  'now_cost_rank': 689,
                  'now_cost_rank_type': 54,
                  'opta_code': 'p463748',
                  'own_goals': 0,
                  'penalties_missed': 0,
                  'penalties_order': None,
                  'penalties_saved': 0,
                  'penalties_text': '',
                  'photo': '463748.jpg',
                  'points_per_game': '0.0',
                  'points_per_game_rank': 598,
                  'points_per_game_rank_type': 75,
                  'price_change_percent': '0',
                  'recoveries': 0,
                  'red_cards': 0,
                  'region': 67,
                  'removed': False,
                  'saves': 0,
                  'saves_per_90': 0,
                  'scout_news_link': '',
                  'scout_risks': [],
                  'second_name': 'Hein',
                  'selected_by_percent': '0.2',
                  'selected_rank': 373,
                  'selected_rank_type': 54,

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [21]:
list(data.keys())

['chips',
 'events',
 'game_settings',
 'game_config',
 'phases',
 'teams',
 'total_players',
 'element_stats',
 'element_types',
 'elements']

In [22]:
players = data['elements']

In [23]:
df_players = pd.json_normalize(players)

In [24]:
ordered_columns = df_players.columns.tolist()
ordered_columns.sort()
ordered_columns

['assists',
 'birth_date',
 'bonus',
 'bps',
 'can_select',
 'can_transact',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'clean_sheets',
 'clean_sheets_per_90',
 'clearances_blocks_interceptions',
 'code',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'creativity',
 'creativity_rank',
 'creativity_rank_type',
 'defensive_contribution',
 'defensive_contribution_per_90',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'expected_assists',
 'expected_assists_per_90',
 'expected_goal_involvements',
 'expected_goal_involvements_per_90',
 'expected_goals',
 'expected_goals_conceded',
 'expected_goals_conceded_per_90',
 'expected_goals_per_90',
 'first_name',
 'form',
 'form_rank',
 'form_rank_type',
 'goals_conceded',
 'goals_conceded_per_90',
 'goals_scored',
 'has_temporary_code',
 'ict_index',
 'ict_index_rank',
 'ict_index_rank_type',
 'id',
 'in_dreamteam',
 'influence',
 'influence_rank',
 'influence_rank_type',
 'known_name',
 'minutes',
 'news',
 'news_added',
 'now_cost',
 'now_cost_rank',
 'now_cost_rank_type',
 'opta_code',
 'own_goals',
 'penalties_missed',
 'penalties_order',
 'penalties_saved',
 'penalties_text',
 'photo',
 'points_per_game',
 'points_per_game_rank',
 'points_per_game_rank_type',
 'price_change_percent',
 'recoveries',
 'red_cards',
 'region',
 'removed',
 'saves',
 'saves_per_90',
 'scout_news_link',
 'scout_risks',
 'second_name',
 'selected_by_percent',
 'selected_rank',
 'selected_rank_type',
 'special',
 'squad_number',
 'starts',
 'starts_per_90',
 'status',
 'tackles',
 'team',
 'team_code',
 'team_join_date',
 'threat',
 'threat_rank',
 'threat_rank_type',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'yellow_cards']

In [25]:
columns = ['id', 'element_type', 'first_name', 'second_name', 'web_name', 'total_points', 'goals_scored', 'assists', 'expected_goals', 'expected_assists']
df_players[columns].sort_values('total_points', ascending=False).head(5)

,id,element_type,first_name,second_name,web_name,total_points,goals_scored,assists,expected_goals,expected_assists
515,430,4,Erling,Haaland,Haaland,197,22,7,21.06,1.94
542,449,3,Bruno,Borges Fernandes,B.Fernandes,189,8,17,10.32,9.03
485,82,3,Antoine,Semenyo,Semenyo,174,15,6,9.93,2.33
4,5,2,Gabriel,dos Santos Magalhães,Gabriel,173,3,4,1.90,1.65
291,249,4,João Pedro,Junqueira de Jesus,João Pedro,164,14,9,13.51,1.88

In [26]:
teams = data['teams']
df_teams = pd.json_normalize(teams)

In [27]:
df_teams.columns.tolist()

['code',
 'draw',
 'form',
 'id',
 'loss',
 'name',
 'played',
 'points',
 'position',
 'short_name',
 'strength',
 'team_division',
 'unavailable',
 'win',
 'strength_overall_home',
 'strength_overall_away',
 'strength_attack_home',
 'strength_attack_away',
 'strength_defence_home',
 'strength_defence_away',
 'pulse_id']

In [28]:
df_teams.sort_values('position').head(5)

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,1,ARS,...,None,False,0,1300,1365,1340,1390,1260,1340,1
12,43,0,None,13,0,Man City,0,0,2,MCI,...,None,False,0,1255,1350,1210,1300,1300,1400,11
13,1,0,None,14,0,Man Utd,0,0,3,MUN,...,None,False,0,1180,1240,1100,1180,1260,1300,12
1,7,0,None,2,0,Aston Villa,0,0,4,AVL,...,None,False,0,1155,1225,1120,1230,1190,1220,2
11,14,0,None,12,0,Liverpool,0,0,5,LIV,...,None,False,0,1215,1245,1170,1210,1260,1280,10

In [29]:
gameweeks = data['events']
df_gw = pd.json_normalize(gameweeks)

In [30]:
df_gw.columns.tolist()

['id',
 'name',
 'deadline_time',
 'release_time',
 'average_entry_score',
 'finished',
 'data_checked',
 'highest_scoring_entry',
 'deadline_time_epoch',
 'deadline_time_game_offset',
 'highest_score',
 'is_previous',
 'is_current',
 'is_next',
 'cup_leagues_created',
 'h2h_ko_matches_created',
 'can_enter',
 'can_manage',
 'released',
 'ranked_count',
 'chip_plays',
 'most_selected',
 'most_transferred_in',
 'top_element',
 'transfers_made',
 'most_captained',
 'most_vice_captained',
 'overrides.element_types',
 'overrides.pick_multiplier',
 'top_element_info.id',
 'top_element_info.points',
 'top_element_info']

In [14]:
df_gw.head()

,id,name,deadline_time,release_time,average_entry_score,finished,data_checked,highest_scoring_entry,deadline_time_epoch,deadline_time_game_offset,...,most_transferred_in,top_element,transfers_made,most_captained,most_vice_captained,overrides.element_types,overrides.pick_multiplier,top_element_info.id,top_element_info.points,top_element_info
0,1,Gameweek 1,2025-08-15T17:30:00Z,None,54,True,True,3772644.0,1755279000,0,...,1.0,531.0,0,381.0,235.0,[],None,531.0,17.0,NaN
1,2,Gameweek 2,2025-08-22T17:30:00Z,None,51,True,True,2963810.0,1755883800,0,...,427.0,8.0,18178809,381.0,235.0,[],None,8.0,24.0,NaN
2,3,Gameweek 3,2025-08-30T10:00:00Z,None,48,True,True,4374360.0,1756548000,0,...,82.0,260.0,27802596,430.0,381.0,[],None,260.0,15.0,NaN
3,4,Gameweek 4,2025-09-13T10:00:00Z,None,63,True,True,7997042.0,1757757600,0,...,419.0,26.0,27408255,381.0,249.0,[],None,26.0,16.0,NaN
4,5,Gameweek 5,2025-09-20T10:00:00Z,None,42,True,True,9985225.0,1758362400,0,...,82.0,660.0,16533109,381.0,249.0,[],None,660.0,15.0,NaN

In [33]:
data = get_json_data('element-summary/430') # Haaland
pprint(data, indent=2)

<Response [200]>
{ 'fixtures': [ { 'code': 2562208,
                  'difficulty': 4,
                  'event': 32,
                  'event_name': 'Gameweek 32',
                  'finished': False,
                  'id': 314,
                  'is_home': False,
                  'kickoff_time': '2026-04-12T15:30:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 13,
                  'team_a_score': None,
                  'team_h': 7,
                  'team_h_score': None},
                { 'code': 2562221,
                  'difficulty': 4,
                  'event': 33,
                  'event_name': 'Gameweek 33',
                  'finished': False,
                  'id': 327,
                  'is_home': True,
                  'kickoff_time': '2026-04-19T15:30:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 1,
                  'team_a_score': None,
                  'team_h': 13,
                  'team_h_score': None},
                { 'code': 2562228,
                  'difficulty': 2,
                  'event': 34,
                  'event_name': 'Gameweek 34',
                  'finished': False,
                  'id': 334,
                  'is_home': False,
                  'kickoff_time': '2026-04-26T13:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 13,
                  'team_a_score': None,
                  'team_h': 3,
                  'team_h_score': None},
                { 'code': 2562240,
                  'difficulty': 3,
                  'event': 35,
                  'event_name': 'Gameweek 35',
                  'finished': False,
                  'id': 346,
                  'is_home': False,
                  'kickoff_time': '2026-05-04T19:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 13,
                  'team_a_score': None,
                  'team_h': 9,
                  'team_h_score': None},
                { 'code': 2562250,
                  'difficulty': 3,
                  'event': 36,
                  'event_name': 'Gameweek 36',
                  'finished': False,
                  'id': 356,
                  'is_home': True,
                  'kickoff_time': '2026-05-09T14:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 5,
                  'team_a_score': None,
                  'team_h': 13,
                  'team_h_score': None},
                { 'code': 2562255,
                  'difficulty': 3,
                  'event': 37,
                  'event_name': 'Gameweek 37',
                  'finished': False,
                  'id': 363,
                  'is_home': False,
                  'kickoff_time': '2026-05-17T14:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 13,
                  'team_a_score': None,
                  'team_h': 4,
                  'team_h_score': None},
                { 'code': 2562270,
                  'difficulty': 3,
                  'event': 38,
                  'event_name': 'Gameweek 38',
                  'finished': False,
                  'id': 376,
                  'is_home': True,
                  'kickoff_time': '2026-05-24T15:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 2,
                  'team_a_score': None,
                  'team_h': 13,
                  'team_h_score': None},
                { 'code': 2562201,
                  'difficulty': 3,
                  'event': None,
                  'finished': False,
                  'id': 307,
                  'is_home': True,
                  'kickoff_time': None,
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 8,
                  'team_a_score': None,
                  'team_h': 13,
                  'team_h_score': None}],
  'history': [ { 'assists': 0,
                 'bonus': 3,
                 'bps': 49,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 0,
                 'creativity': '0.3',
                 'defensive_contribution': 2,
                 'element': 430,
                 'expected_assists': '0.00',
                 'expected_goal_involvements': '1.99',
                 'expected_goals': '1.99',
                 'expected_goals_conceded': '0.35',
                 'fixture': 7,
                 'goals_conceded': 0,
                 'goals_scored': 2,
                 'ict_index': '12.9',
                 'influence': '58.0',
                 'kickoff_time': '2025-08-16T16:30:00Z',
                 'minutes': 72,
                 'modified': False,
                 'opponent_team': 20,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 1,
                 'red_cards': 0,
                 'round': 1,
                 'saves': 0,
                 'selected': 2283987,
                 'starts': 1,
                 'tackles': 1,
                 'team_a_score': 4,
                 'team_h_score': 0,
                 'threat': '71.0',
                 'total_points': 13,
                 'transfers_balance': 0,
                 'transfers_in': 0,
                 'transfers_out': 0,
                 'value': 140,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 0,
                 'bps': 6,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 1,
                 'creativity': '15.2',
                 'defensive_contribution': 4,
                 'element': 430,
                 'expected_assists': '0.30',
                 'expected_goal_involvements': '0.77',
                 'expected_goals': '0.47',
                 'expected_goals_conceded': '1.11',
                 'fixture': 18,
                 'goals_conceded': 2,
                 'goals_scored': 0,
                 'ict_index': '3.2',
                 'influence': '1.4',
                 'kickoff_time': '2025-08-23T11:30:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 18,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 3,
                 'red_cards': 0,
                 'round': 2,
                 'saves': 0,
                 'selected': 3276879,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 2,
                 'team_h_score': 0,
                 'threat': '15.0',
                 'total_points': 2,
                 'transfers_balance': 396573,
                 'transfers_in': 446334,
                 'transfers_out': 49761,
                 'value': 140,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 29,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 0,
                 'creativity': '0.4',
                 'defensive_contribution': 1,
                 'element': 430,
                 'expected_assists': '0.00',
                 'expected_goal_involvements': '1.40',
                 'expected_goals': '1.40',
                 'expected_goals_conceded': '2.30',
                 'fixture': 22,
                 'goals_conceded': 2,
                 'goals_scored': 1,
                 'ict_index': '12.7',
                 'influence': '30.4',
                 'kickoff_time': '2025-08-31T13:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 6,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 1,
                 'red_cards': 0,
                 'round': 3,
                 'saves': 0,
                 'selected': 3747441,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 2,
                 'threat': '96.0',
                 'total_points': 9,
                 'transfers_balance': 179096,
                 'transfers_in': 366370,
                 'transfers_out': 187274,
                 'value': 141,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 63,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 6,
                 'creativity': '12.9',
                 'defensive_contribution': 8,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '1.81',
                 'expected_goals': '1.80',
                 'expected_goals_conceded': '1.42',
                 'fixture': 38,
                 'goals_conceded': 0,
                 'goals_scored': 2,
                 'ict_index': '16.2',
                 'influence': '78.8',
                 'kickoff_time': '2025-09-14T15:30:00Z',
                 'minutes': 86,
                 'modified': False,
                 'opponent_team': 14,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 2,
                 'red_cards': 0,
                 'round': 4,
                 'saves': 0,
                 'selected': 3931425,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 0,
                 'team_h_score': 3,
                 'threat': '70.0',
                 'total_points': 13,
                 'transfers_balance': 209666,
                 'transfers_in': 435454,
                 'transfers_out': 225788,
                 'value': 141,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 32,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '2.1',
                 'defensive_contribution': 5,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '0.53',
                 'expected_goals': '0.52',
                 'expected_goals_conceded': '0.77',
                 'fixture': 41,
                 'goals_conceded': 0,
                 'goals_scored': 1,
                 'ict_index': '7.2',
                 'influence': '35.4',
                 'kickoff_time': '2025-09-21T15:30:00Z',
                 'minutes': 75,
                 'modified': False,
                 'opponent_team': 1,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 3,
                 'red_cards': 0,
                 'round': 5,
                 'saves': 0,
                 'selected': 4419019,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 1,
                 'threat': '34.0',
                 'total_points': 9,
                 'transfers_balance': 405468,
                 'transfers_in': 479550,
                 'transfers_out': 74082,
                 'value': 142,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 1,
                 'bonus': 3,
                 'bps': 68,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '20.8',
                 'defensive_contribution': 4,
                 'element': 430,
                 'expected_assists': '0.24',
                 'expected_goal_involvements': '1.41',
                 'expected_goals': '1.17',
                 'expected_goals_conceded': '0.41',
                 'fixture': 57,
                 'goals_conceded': 1,
                 'goals_scored': 2,
                 'ict_index': '18.4',
                 'influence': '85.4',
                 'kickoff_time': '2025-09-27T14:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 3,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 2,
                 'red_cards': 0,
                 'round': 6,
                 'saves': 0,
                 'selected': 5991428,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 5,
                 'threat': '78.0',
                 'total_points': 16,
                 'transfers_balance': 1415070,
                 'transfers_in': 1490551,
                 'transfers_out': 75481,
                 'value': 143,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 2,
                 'bps': 36,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '3.4',
                 'defensive_contribution': 2,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '0.30',
                 'expected_goals': '0.29',
                 'expected_goals_conceded': '0.83',
                 'fixture': 64,
                 'goals_conceded': 0,
                 'goals_scored': 1,
                 'ict_index': '6.2',
                 'influence': '35.4',
                 'kickoff_time': '2025-10-05T15:30:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 5,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 0,
                 'red_cards': 0,
                 'round': 7,
                 'saves': 0,
                 'selected': 7060510,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 0,
                 'threat': '23.0',
                 'total_points': 8,
                 'transfers_balance': 1031965,
                 'transfers_in': 1038671,
                 'transfers_out': 6706,
                 'value': 144,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 62,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '1.9',
                 'defensive_contribution': 4,
                 'element': 430,
                 'expected_assists': '0.02',
                 'expected_goal_involvements': '1.00',
                 'expected_goals': '0.98',
                 'expected_goals_conceded': '0.81',
                 'fixture': 76,
                 'goals_conceded': 0,
                 'goals_scored': 2,
                 'ict_index': '16.4',
                 'influence': '77.4',
                 'kickoff_time': '2025-10-18T14:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 9,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 2,
                 'red_cards': 0,
                 'round': 8,
                 'saves': 0,
                 'selected': 7826831,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 0,
                 'team_h_score': 2,
                 'threat': '85.0',
                 'total_points': 13,
                 'transfers_balance': 707569,
                 'transfers_in': 717731,
                 'transfers_out': 10162,
                 'value': 146,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 0,
                 'bps': 9,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 3,
                 'creativity': '2.6',
                 'defensive_contribution': 3,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '0.24',
                 'expected_goals': '0.23',
                 'expected_goals_conceded': '0.81',
                 'fixture': 82,
                 'goals_conceded': 1,
                 'goals_scored': 0,
                 'ict_index': '7.1',
                 'influence': '15.2',
                 'kickoff_time': '2025-10-26T14:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 2,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 0,
                 'red_cards': 0,
                 'round': 9,
                 'saves': 0,
                 'selected': 8327859,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 0,
                 'team_h_score': 1,
                 'threat': '53.0',
                 'total_points': 2,
                 'transfers_balance': 470274,
                 'transfers_in': 478726,
                 'transfers_out': 8452,
                 'value': 147,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 62,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 1,
                 'creativity': '3.8',
                 'defensive_contribution': 1,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '1.34',
                 'expected_goals': '1.33',
                 'expected_goals_conceded': '0.71',
                 'fixture': 96,
                 'goals_conceded': 1,
                 'goals_scored': 2,
                 'ict_index': '15.7',
                 'influence': '71.6',
                 'kickoff_time': '2025-11-02T16:30:00Z',
                 'minutes': 81,
                 'modified': False,
                 'opponent_team': 4,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 0,
                 'red_cards': 0,
                 'round': 10,
                 'saves': 0,
                 'selected': 8565665,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 3,
                 'threat': '82.0',
                 'total_points': 13,
                 'transfers_balance': 202821,
                 'transfers_in': 228200,
                 'transfers_out': 25379,
                 'value': 148,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 0,
                 'bps': 28,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 1,
                 'creativity': '1.6',
                 'defensive_contribution': 2,
                 'element': 430,

In [34]:
df_history = pd.json_normalize(data['history'])
df_history.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,...,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out
0,430,7,20,13,False,2025-08-16T16:30:00Z,0,4,1,False,...,1,1.99,0.00,1.99,0.35,140,0,2283987,0,0
1,430,18,18,2,True,2025-08-23T11:30:00Z,0,2,2,False,...,1,0.47,0.30,0.77,1.11,140,396573,3276879,446334,49761
2,430,22,6,9,False,2025-08-31T13:00:00Z,2,1,3,False,...,1,1.40,0.00,1.40,2.30,141,179096,3747441,366370,187274
3,430,38,14,13,True,2025-09-14T15:30:00Z,3,0,4,False,...,1,1.80,0.01,1.81,1.42,141,209666,3931425,435454,225788
4,430,41,1,9,False,2025-09-21T15:30:00Z,1,1,5,False,...,1,0.52,0.01,0.53,0.77,142,405468,4419019,479550,74082

In [36]:
data = get_json_data('event/5/live')
pprint(data, indent=2)

<Response [200]>
{ 'elements': [ { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 90}]}],
                  'id': 1,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 13,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 1,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.01',
                             'expected_goal_involvements': '0.01',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.89',
                             'goals_conceded': 1,
                             'goals_scored': 0,
                             'ict_index': '2.1',
                             'in_dreamteam': False,
                             'influence': '21.4',
                             'minutes': 90,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 6,
                             'red_cards': 0,
                             'saves': 2,
                             'starts': 1,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 2,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 2,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 3,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 4,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 90}]}],
                  'id': 5,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 13,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 7,
                             'creativity': '2.3',
                             'defensive_contribution': 8,
                             'expected_assists': '0.01',
                             'expected_goal_involvements': '0.01',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.89',
                             'goals_conceded': 1,
                             'goals_scored': 0,
                             'ict_index': '2.2',
                             'in_dreamteam': False,
                             'influence': '19.6',
                             'minutes': 90,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 1,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 1,
                             'tackles': 1,
                             'threat': '0.0',
                             'total_points': 2,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 90}]}],
                  'id': 6,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 15,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 5,
                             'creativity': '3.0',
                             'defensive_contribution': 9,
                             'expected_assists': '0.02',
                             'expected_goal_involvements': '0.15',
                             'expected_goals': '0.13',
                             'expected_goals_conceded': '0.89',
                             'goals_conceded': 1,
                             'goals_scored': 0,
                             'ict_index': '2.9',
                             'in_dreamteam': False,
                             'influence': '22.0',
                             'minutes': 90,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 8,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 1,
                             'tackles': 4,
                             'threat': '4.0',
                             'total_points': 2,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 90}]}],
                  'id': 7,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 7,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 2,
                             'creativity': '6.2',
                             'defensive_contribution': 5,
                             'expected_assists': '0.05',
                             'expected_goal_involvements': '0.19',
                             'expected_goals': '0.14',
                             'expected_goals_conceded': '0.89',
                             'goals_conceded': 1,
                             'goals_scored': 0,
                             'ict_index': '2.9',
                             'in_dreamteam': False,
                             'influence': '3.6',
                             'minutes': 90,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 6,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 1,
                             'tackles': 3,
                             'threat': '19.0',
                             'total_points': 2,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 79},
                                            { 'identifier': 'yellow_cards',
                                              'points': -1,
                                              'points_modification': 0,
                                              'value': 1}]}],
                  'id': 8,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 16,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 1,
                             'creativity': '13.9',
                             'defensive_contribution': 8,
                             'expected_assists': '0.05',
                             'expected_goal_involvements': '0.05',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.65',
                             'goals_conceded': 1,
                             'goals_scored': 0,
                             'ict_index': '3.9',
                             'in_dreamteam': False,
                             'influence': '17.0',
                             'minutes': 79,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 3,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 1,
                             'tackles': 7,
                             'threat': '8.0',
                             'total_points': 1,
                             'yellow_cards': 1}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 9,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 10,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 41,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 11,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 44,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,