In [1]:
import requests
import pandas as pd
import json
from pprint import pprint

In [2]:
base_url = 'https://fantasy.premierleague.com/api/'

In [3]:
def get_json_data(endpoint: str):
    response = requests.get(base_url+endpoint)
    print(response)
    return response.json()

In [4]:
data = get_json_data('bootstrap-static')
pprint(data, indent=2)

<Response [200]>
{ 'chips': [ { 'chip_type': 'transfer',
               'id': 1,
               'name': 'wildcard',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 2,
               'stop_event': 19},
             { 'chip_type': 'transfer',
               'id': 2,
               'name': 'wildcard',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38},
             { 'chip_type': 'transfer',
               'id': 3,
               'name': 'freehit',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 2,
               'stop_event': 19},
             { 'chip_type': 'team',
               'id': 4,
               'name': 'bboost',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 1,
               'stop_event': 19},
             { 'chip_type': 'team',
               'id': 5,
               'name': '3xc',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 1,
               'stop_event': 19},
             { 'chip_type': 'transfer',
               'id': 6,
               'name': 'freehit',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38},
             { 'chip_type': 'team',
               'id': 7,
               'name': 'bboost',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38},
             { 'chip_type': 'team',
               'id': 8,
               'name': '3xc',
               'number': 1,
               'overrides': { 'element_types': [],
                              'pick_multiplier': None,
                              'rules': {},
                              'scoring': {}},
               'start_event': 20,
               'stop_event': 38}],
  'element_stats': [ {'label': 'Minutes played', 'name': 'minutes'},
                     {'label': 'Goals scored', 'name': 'goals_scored'},
                     {'label': 'Assists', 'name': 'assists'},
                     {'label': 'Clean sheets', 'name': 'clean_sheets'},
                     {'label': 'Goals conceded', 'name': 'goals_conceded'},
                     {'label': 'Own goals', 'name': 'own_goals'},
                     {'label': 'Penalties saved', 'name': 'penalties_saved'},
                     {'label': 'Penalties missed', 'name': 'penalties_missed'},
                     {'label': 'Yellow cards', 'name': 'yellow_cards'},
                     {'label': 'Red cards', 'name': 'red_cards'},
                     {'label': 'Saves', 'name': 'saves'},
                     {'label': 'Bonus', 'name': 'bonus'},
                     {'label': 'Bonus Points System', 'name': 'bps'},
                     {'label': 'Influence', 'name': 'influence'},
                     {'label': 'Creativity', 'name': 'creativity'},
                     {'label': 'Threat', 'name': 'threat'},
                     {'label': 'ICT Index', 'name': 'ict_index'},
                     { 'label': 'Clearances, blocks and interceptions',
                       'name': 'clearances_blocks_interceptions'},
                     {'label': 'Recoveries', 'name': 'recoveries'},
                     {'label': 'Tackles', 'name': 'tackles'},
                     { 'label': 'Defensive Contribution',
                       'name': 'defensive_contribution'},
                     {'label': 'Game(s) Started', 'name': 'starts'},
                     {'label': 'Expected Goals', 'name': 'expected_goals'},
                     {'label': 'Expected Assists', 'name': 'expected_assists'},
                     { 'label': 'Expected Goal Involvements',
                       'name': 'expected_goal_involvements'},
                     { 'label': 'Expected Goals Conceded',
                       'name': 'expected_goals_conceded'}],
  'element_types': [ { 'element_count': 96,
                       'id': 1,
                       'plural_name': 'Goalkeepers',
                       'plural_name_short': 'GKP',
                       'singular_name': 'Goalkeeper',
                       'singular_name_short': 'GKP',
                       'squad_max_play': 1,
                       'squad_max_select': None,
                       'squad_min_play': 1,
                       'squad_min_select': None,
                       'squad_select': 2,
                       'sub_positions_locked': [12],
                       'ui_shirt_specific': True},
                     { 'element_count': 268,
                       'id': 2,
                       'plural_name': 'Defenders',
                       'plural_name_short': 'DEF',
                       'singular_name': 'Defender',
                       'singular_name_short': 'DEF',
                       'squad_max_play': 5,
                       'squad_max_select': None,
                       'squad_min_play': 3,
                       'squad_min_select': None,
                       'squad_select': 5,
                       'sub_positions_locked': [],
                       'ui_shirt_specific': False},
                     { 'element_count': 373,
                       'id': 3,
                       'plural_name': 'Midfielders',
                       'plural_name_short': 'MID',
                       'singular_name': 'Midfielder',
                       'singular_name_short': 'MID',
                       'squad_max_play': 5,
                       'squad_max_select': None,
                       'squad_min_play': 2,
                       'squad_min_select': None,
                       'squad_select': 5,
                       'sub_positions_locked': [],
                       'ui_shirt_specific': False},
                     { 'element_count': 93,
                       'id': 4,
                       'plural_name': 'Forwards',
                       'plural_name_short': 'FWD',
                       'singular_name': 'Forward',
                       'singular_name_short': 'FWD',
                       'squad_max_play': 3,
                       'squad_max_select': None,
                       'squad_min_play': 1,
                       'squad_min_select': None,
                       'squad_select': 3,
                       'sub_positions_locked': [],
                       'ui_shirt_specific': False}],
  'elements': [ { 'assists': 0,
                  'birth_date': '1995-09-15',
                  'bonus': 9,
                  'bps': 562,
                  'can_select': True,
                  'can_transact': True,
                  'chance_of_playing_next_round': None,
                  'chance_of_playing_this_round': None,
                  'clean_sheets': 16,
                  'clean_sheets_per_90': 0.47,
                  'clearances_blocks_interceptions': 33,
                  'code': 154561,
                  'corners_and_indirect_freekicks_order': None,
                  'corners_and_indirect_freekicks_text': '',
                  'cost_change_event': 0,
                  'cost_change_event_fall': 0,
                  'cost_change_start': 5,
                  'cost_change_start_fall': -5,
                  'creativity': '33.4',
                  'creativity_rank': 383,
                  'creativity_rank_type': 3,
                  'defensive_contribution': 0,
                  'defensive_contribution_per_90': 0.0,
                  'direct_freekicks_order': None,
                  'direct_freekicks_text': '',
                  'dreamteam_count': 2,
                  'element_type': 1,
                  'ep_next': '5.0',
                  'ep_this': '5.0',
                  'event_points': 10,
                  'expected_assists': '0.06',
                  'expected_assists_per_90': 0.0,
                  'expected_goal_involvements': '0.06',
                  'expected_goal_involvements_per_90': 0.0,
                  'expected_goals': '0.00',
                  'expected_goals_conceded': '25.85',
                  'expected_goals_conceded_per_90': 0.76,
                  'expected_goals_per_90': 0.0,
                  'first_name': 'David',
                  'form': '4.0',
                  'form_rank': 82,
                  'form_rank_type': 9,
                  'goals_conceded': 26,
                  'goals_conceded_per_90': 0.76,
                  'goals_scored': 0,
                  'has_temporary_code': False,
                  'ict_index': '53.8',
                  'ict_index_rank': 270,
                  'ict_index_rank_type': 17,
                  'id': 1,
                  'in_dreamteam': True,
                  'influence': '504.4',
                  'influence_rank': 102,
                  'influence_rank_type': 17,
                  'known_name': '',
                  'minutes': 3060,
                  'news': '',
                  'news_added': None,
                  'now_cost': 60,
                  'now_cost_rank': 86,
                  'now_cost_rank_type': 1,
                  'opta_code': 'p154561',
                  'own_goals': 0,
                  'penalties_missed': 0,
                  'penalties_order': None,
                  'penalties_saved': 0,
                  'penalties_text': '',
                  'photo': '154561.jpg',
                  'points_per_game': '4.1',
                  'points_per_game_rank': 56,
                  'points_per_game_rank_type': 4,
                  'price_change_percent': '0',
                  'recoveries': 290,
                  'red_cards': 0,
                  'region': 200,
                  'removed': False,
                  'saves': 56,
                  'saves_per_90': 1.65,
                  'scout_news_link': '',
                  'scout_risks': [],
                  'second_name': 'Raya Martín',
                  'selected_by_percent': '34.3',
                  'selected_rank': 7,
                  'selected_rank_type': 1,
                  'special': False,
                  'squad_number': None,
                  'starts': 34,
                  'starts_per_90': 1.0,
                  'status': 'a',
                  'tackles': 1,
                  'team': 1,
                  'team_code': 3,
                  'team_join_date': '2024-07-04',
                  'threat': '0.0',
                  'threat_rank': 821,
                  'threat_rank_type': 96,
                  'total_points': 141,
                  'transfers_in': 4483222,
                  'transfers_in_event': 69515,
                  'transfers_out': 2835455,
                  'transfers_out_event': 12127,
                  'value_form': '0.7',
                  'value_season': '23.5',
                  'web_name': 'Raya',
                  'yellow_cards': 1},
                { 'assists': 0,
                  'birth_date': '1994-10-03',
                  'bonus': 0,
                  'bps': 0,
                  'can_select': True,
                  'can_transact': True,
                  'chance_of_playing_next_round': None,
                  'chance_of_playing_this_round': None,
                  'clean_sheets': 0,
                  'clean_sheets_per_90': 0,
                  'clearances_blocks_interceptions': 0,
                  'code': 109745,
                  'corners_and_indirect_freekicks_order': None,
                  'corners_and_indirect_freekicks_text': '',
                  'cost_change_event': 0,
                  'cost_change_event_fall': 0,
                  'cost_change_start': -5,
                  'cost_change_start_fall': 5,
                  'creativity': '0.0',
                  'creativity_rank': 562,
                  'creativity_rank_type': 53,
                  'defensive_contribution': 0,
                  'defensive_contribution_per_90': 0,
                  'direct_freekicks_order': None,
                  'direct_freekicks_text': '',
                  'dreamteam_count': 0,
                  'element_type': 1,
                  'ep_next': '1.0',
                  'ep_this': '1.0',
                  'event_points': 0,
                  'expected_assists': '0.00',
                  'expected_assists_per_90': 0,
                  'expected_goal_involvements': '0.00',
                  'expected_goal_involvements_per_90': 0,
                  'expected_goals': '0.00',
                  'expected_goals_conceded': '0.00',
                  'expected_goals_conceded_per_90': 0,
                  'expected_goals_per_90': 0,
                  'first_name': 'Kepa',
                  'form': '0.0',
                  'form_rank': 432,
                  'form_rank_type': 55,
                  'goals_conceded': 0,
                  'goals_conceded_per_90': 0,
                  'goals_scored': 0,
                  'has_temporary_code': False,
                  'ict_index': '0.0',
                  'ict_index_rank': 573,
                  'ict_index_rank_type': 66,
                  'id': 2,
                  'in_dreamteam': False,
                  'influence': '0.0',
                  'influence_rank': 571,
                  'influence_rank_type': 66,
                  'known_name': '',
                  'minutes': 0,
                  'news': '',
                  'news_added': None,
                  'now_cost': 40,
                  'now_cost_rank': 671,
                  'now_cost_rank_type': 43,
                  'opta_code': 'p109745',
                  'own_goals': 0,
                  'penalties_missed': 0,
                  'penalties_order': None,
                  'penalties_saved': 0,
                  'penalties_text': '',
                  'photo': '109745.jpg',
                  'points_per_game': '0.0',
                  'points_per_game_rank': 582,
                  'points_per_game_rank_type': 66,
                  'price_change_percent': '0',
                  'recoveries': 0,
                  'red_cards': 0,
                  'region': 200,
                  'removed': False,
                  'saves': 0,
                  'saves_per_90': 0,
                  'scout_news_link': '',
                  'scout_risks': [],
                  'second_name': 'Arrizabalaga Revuelta',
                  'selected_by_percent': '0.4',
                  'selected_rank': 293,
                  'selected_rank_type': 38,
                  'special': False,
                  'squad_number': None,
                  'starts': 0,
                  'starts_per_90': 0,
                  'status': 'a',
                  'tackles': 0,
                  'team': 1,
                  'team_code': 3,
                  'team_join_date': '2025-07-01',
                  'threat': '0.0',
                  'threat_rank': 531,
                  'threat_rank_type': 39,
                  'total_points': 0,
                  'transfers_in': 15848,
                  'transfers_in_event': 116,
                  'transfers_out': 78542,
                  'transfers_out_event': 141,
                  'value_form': '0.0',
                  'value_season': '0.0',
                  'web_name': 'Arrizabalaga',
                  'yellow_cards': 0},
                { 'assists': 0,
                  'birth_date': '2002-04-13',
                  'bonus': 0,
                  'bps': 0,
                  'can_select': False,
                  'can_transact': True,
                  'chance_of_playing_next_round': 0,
                  'chance_of_playing_this_round': 0,
                  'clean_sheets': 0,
                  'clean_sheets_per_90': 0,
                  'clearances_blocks_interceptions': 0,
                  'code': 463748,
                  'corners_and_indirect_freekicks_order': None,
                  'corners_and_indirect_freekicks_text': '',
                  'cost_change_event': 0,
                  'cost_change_event_fall': 0,
                  'cost_change_start': 0,
                  'cost_change_start_fall': 0,
                  'creativity': '0.0',
                  'creativity_rank': 580,
                  'creativity_rank_type': 63,
                  'defensive_contribution': 0,
                  'defensive_contribution_per_90': 0,
                  'direct_freekicks_order': None,
                  'direct_freekicks_text': '',
                  'dreamteam_count': 0,
                  'element_type': 1,
                  'ep_next': '0.0',
                  'ep_this': '0.0',
                  'event_points': 0,
                  'expected_assists': '0.00',
                  'expected_assists_per_90': 0,
                  'expected_goal_involvements': '0.00',
                  'expected_goal_involvements_per_90': 0,
                  'expected_goals': '0.00',
                  'expected_goals_conceded': '0.00',
                  'expected_goals_conceded_per_90': 0,
                  'expected_goals_per_90': 0,
                  'first_name': 'Karl',
                  'form': '0.0',
                  'form_rank': 451,
                  'form_rank_type': 65,
                  'goals_conceded': 0,
                  'goals_conceded_per_90': 0,
                  'goals_scored': 0,
                  'has_temporary_code': False,
                  'ict_index': '0.0',
                  'ict_index_rank': 590,
                  'ict_index_rank_type': 75,
                  'id': 3,
                  'in_dreamteam': False,
                  'influence': '0.0',
                  'influence_rank': 588,
                  'influence_rank_type': 75,
                  'known_name': '',
                  'minutes': 0,
                  'news': 'Has joined Werder Bremen on loan for the rest of '
                          'the season.',
                  'news_added': '2025-08-26T13:44:02.357864Z',
                  'now_cost': 40,
                  'now_cost_rank': 691,
                  'now_cost_rank_type': 53,
                  'opta_code': 'p463748',
                  'own_goals': 0,
                  'penalties_missed': 0,
                  'penalties_order': None,
                  'penalties_saved': 0,
                  'penalties_text': '',
                  'photo': '463748.jpg',
                  'points_per_game': '0.0',
                  'points_per_game_rank': 599,
                  'points_per_game_rank_type': 75,
                  'price_change_percent': '0',
                  'recoveries': 0,
                  'red_cards': 0,
                  'region': 67,
                  'removed': False,
                  'saves': 0,
                  'saves_per_90': 0,
                  'scout_news_link': '',
                  'scout_risks': [],
                  'second_name': 'Hein',
                  'selected_by_percent': '0.2',
                  'selected_rank': 380,
                  'selected_rank_type': 54,

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [5]:
list(data.keys())

['chips',
 'events',
 'game_settings',
 'game_config',
 'phases',
 'teams',
 'total_players',
 'element_stats',
 'element_types',
 'elements']

In [6]:
players = data['elements']

In [7]:
df_players = pd.json_normalize(players)

In [8]:
ordered_columns = df_players.columns.tolist()
ordered_columns.sort()
ordered_columns

['assists',
 'birth_date',
 'bonus',
 'bps',
 'can_select',
 'can_transact',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'clean_sheets',
 'clean_sheets_per_90',
 'clearances_blocks_interceptions',
 'code',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'creativity',
 'creativity_rank',
 'creativity_rank_type',
 'defensive_contribution',
 'defensive_contribution_per_90',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'expected_assists',
 'expected_assists_per_90',
 'expected_goal_involvements',
 'expected_goal_involvements_per_90',
 'expected_goals',
 'expected_goals_conceded',
 'expected_goals_conceded_per_90',
 'expected_goals_per_90',
 'first_name',
 'form',
 'form_rank',
 'form_rank_type',
 'goals_conceded',
 'goals_conceded_per_90',
 'goals_scored',
 'has_temporary_code',
 'ict_index',
 'ict_index_rank',
 'ict_index_rank_type',
 'id',
 'in_dreamteam',
 'influence',
 'influence_rank',
 'influence_rank_type',
 'known_name',
 'minutes',
 'news',
 'news_added',
 'now_cost',
 'now_cost_rank',
 'now_cost_rank_type',
 'opta_code',
 'own_goals',
 'penalties_missed',
 'penalties_order',
 'penalties_saved',
 'penalties_text',
 'photo',
 'points_per_game',
 'points_per_game_rank',
 'points_per_game_rank_type',
 'price_change_percent',
 'recoveries',
 'red_cards',
 'region',
 'removed',
 'saves',
 'saves_per_90',
 'scout_news_link',
 'scout_risks',
 'second_name',
 'selected_by_percent',
 'selected_rank',
 'selected_rank_type',
 'special',
 'squad_number',
 'starts',
 'starts_per_90',
 'status',
 'tackles',
 'team',
 'team_code',
 'team_join_date',
 'threat',
 'threat_rank',
 'threat_rank_type',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'yellow_cards']

In [9]:
columns = ['id', 'element_type', 'first_name', 'second_name', 'web_name', 'total_points', 'goals_scored', 'assists', 'expected_goals', 'expected_assists']
df_players[columns].sort_values('total_points', ascending=False).head(5)

,id,element_type,first_name,second_name,web_name,total_points,goals_scored,assists,expected_goals,expected_assists
518,430,4,Erling,Haaland,Haaland,212,24,7,23.52,2.05
545,449,3,Bruno,Borges Fernandes,B.Fernandes,204,8,20,10.38,10.21
4,5,2,Gabriel,dos Santos Magalhães,Gabriel,185,3,5,2.00,1.68
488,82,3,Antoine,Semenyo,Semenyo,181,15,6,10.54,2.67
19,21,3,Declan,Rice,Rice,171,4,9,3.15,6.85

In [10]:
teams = data['teams']
df_teams = pd.json_normalize(teams)

In [11]:
df_teams.columns.tolist()

['code',
 'draw',
 'form',
 'id',
 'loss',
 'name',
 'played',
 'points',
 'position',
 'short_name',
 'strength',
 'team_division',
 'unavailable',
 'win',
 'strength_overall_home',
 'strength_overall_away',
 'strength_attack_home',
 'strength_attack_away',
 'strength_defence_home',
 'strength_defence_away',
 'pulse_id']

In [12]:
df_teams.sort_values('position').head(5)

,code,draw,form,id,loss,name,played,points,position,short_name,...,team_division,unavailable,win,strength_overall_home,strength_overall_away,strength_attack_home,strength_attack_away,strength_defence_home,strength_defence_away,pulse_id
0,3,0,None,1,0,Arsenal,0,0,1,ARS,...,None,False,0,1305,1355,1340,1390,1270,1320,1
12,43,0,None,13,0,Man City,0,0,2,MCI,...,None,False,0,1265,1355,1220,1310,1310,1400,11
13,1,0,None,14,0,Man Utd,0,0,3,MUN,...,None,False,0,1180,1250,1120,1190,1240,1310,12
11,14,0,None,12,0,Liverpool,0,0,4,LIV,...,None,False,0,1180,1250,1120,1200,1240,1300,10
1,7,0,None,2,0,Aston Villa,0,0,5,AVL,...,None,False,0,1135,1230,1120,1210,1150,1250,2

In [13]:
gameweeks = data['events']
df_gw = pd.json_normalize(gameweeks)

In [14]:
df_gw.columns.tolist()

['id',
 'name',
 'deadline_time',
 'release_time',
 'average_entry_score',
 'finished',
 'data_checked',
 'highest_scoring_entry',
 'deadline_time_epoch',
 'deadline_time_game_offset',
 'highest_score',
 'is_previous',
 'is_current',
 'is_next',
 'cup_leagues_created',
 'h2h_ko_matches_created',
 'can_enter',
 'can_manage',
 'released',
 'ranked_count',
 'chip_plays',
 'most_selected',
 'most_transferred_in',
 'top_element',
 'transfers_made',
 'most_captained',
 'most_vice_captained',
 'overrides.element_types',
 'overrides.pick_multiplier',
 'top_element_info.id',
 'top_element_info.points',
 'top_element_info']

In [15]:
df_gw.head()

,id,name,deadline_time,release_time,average_entry_score,finished,data_checked,highest_scoring_entry,deadline_time_epoch,deadline_time_game_offset,...,most_transferred_in,top_element,transfers_made,most_captained,most_vice_captained,overrides.element_types,overrides.pick_multiplier,top_element_info.id,top_element_info.points,top_element_info
0,1,Gameweek 1,2025-08-15T17:30:00Z,None,54,True,True,3772644.0,1755279000,0,...,1.0,531.0,0,381.0,235.0,[],None,531.0,17.0,NaN
1,2,Gameweek 2,2025-08-22T17:30:00Z,None,51,True,True,2963810.0,1755883800,0,...,427.0,8.0,18178809,381.0,235.0,[],None,8.0,24.0,NaN
2,3,Gameweek 3,2025-08-30T10:00:00Z,None,48,True,True,4374360.0,1756548000,0,...,82.0,260.0,27802596,430.0,381.0,[],None,260.0,15.0,NaN
3,4,Gameweek 4,2025-09-13T10:00:00Z,None,63,True,True,7997042.0,1757757600,0,...,419.0,26.0,27408255,381.0,249.0,[],None,26.0,16.0,NaN
4,5,Gameweek 5,2025-09-20T10:00:00Z,None,42,True,True,9985225.0,1758362400,0,...,82.0,660.0,16533109,381.0,249.0,[],None,660.0,15.0,NaN

In [16]:
data = get_json_data('element-summary/430') # Haaland
pprint(data, indent=2)

<Response [200]>
{ 'fixtures': [ { 'code': 2562240,
                  'difficulty': 3,
                  'event': 35,
                  'event_name': 'Gameweek 35',
                  'finished': False,
                  'id': 346,
                  'is_home': False,
                  'kickoff_time': '2026-05-04T19:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 13,
                  'team_a_score': None,
                  'team_h': 9,
                  'team_h_score': None},
                { 'code': 2562250,
                  'difficulty': 3,
                  'event': 36,
                  'event_name': 'Gameweek 36',
                  'finished': False,
                  'id': 356,
                  'is_home': True,
                  'kickoff_time': '2026-05-09T16:30:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 5,
                  'team_a_score': None,
                  'team_h': 13,
                  'team_h_score': None},
                { 'code': 2562201,
                  'difficulty': 3,
                  'event': 36,
                  'event_name': 'Gameweek 36',
                  'finished': False,
                  'id': 307,
                  'is_home': True,
                  'kickoff_time': '2026-05-13T19:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 8,
                  'team_a_score': None,
                  'team_h': 13,
                  'team_h_score': None},
                { 'code': 2562255,
                  'difficulty': 4,
                  'event': 37,
                  'event_name': 'Gameweek 37',
                  'finished': False,
                  'id': 363,
                  'is_home': False,
                  'kickoff_time': '2026-05-19T18:30:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 13,
                  'team_a_score': None,
                  'team_h': 4,
                  'team_h_score': None},
                { 'code': 2562270,
                  'difficulty': 3,
                  'event': 38,
                  'event_name': 'Gameweek 38',
                  'finished': False,
                  'id': 376,
                  'is_home': True,
                  'kickoff_time': '2026-05-24T15:00:00Z',
                  'minutes': 0,
                  'provisional_start_time': False,
                  'team_a': 2,
                  'team_a_score': None,
                  'team_h': 13,
                  'team_h_score': None}],
  'history': [ { 'assists': 0,
                 'bonus': 3,
                 'bps': 49,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 0,
                 'creativity': '0.3',
                 'defensive_contribution': 2,
                 'element': 430,
                 'expected_assists': '0.00',
                 'expected_goal_involvements': '1.99',
                 'expected_goals': '1.99',
                 'expected_goals_conceded': '0.35',
                 'fixture': 7,
                 'goals_conceded': 0,
                 'goals_scored': 2,
                 'ict_index': '12.9',
                 'influence': '58.0',
                 'kickoff_time': '2025-08-16T16:30:00Z',
                 'minutes': 72,
                 'modified': False,
                 'opponent_team': 20,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 1,
                 'red_cards': 0,
                 'round': 1,
                 'saves': 0,
                 'selected': 2283987,
                 'starts': 1,
                 'tackles': 1,
                 'team_a_score': 4,
                 'team_h_score': 0,
                 'threat': '71.0',
                 'total_points': 13,
                 'transfers_balance': 0,
                 'transfers_in': 0,
                 'transfers_out': 0,
                 'value': 140,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 0,
                 'bps': 6,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 1,
                 'creativity': '15.2',
                 'defensive_contribution': 4,
                 'element': 430,
                 'expected_assists': '0.30',
                 'expected_goal_involvements': '0.77',
                 'expected_goals': '0.47',
                 'expected_goals_conceded': '1.11',
                 'fixture': 18,
                 'goals_conceded': 2,
                 'goals_scored': 0,
                 'ict_index': '3.2',
                 'influence': '1.4',
                 'kickoff_time': '2025-08-23T11:30:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 18,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 3,
                 'red_cards': 0,
                 'round': 2,
                 'saves': 0,
                 'selected': 3276879,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 2,
                 'team_h_score': 0,
                 'threat': '15.0',
                 'total_points': 2,
                 'transfers_balance': 396573,
                 'transfers_in': 446334,
                 'transfers_out': 49761,
                 'value': 140,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 29,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 0,
                 'creativity': '0.4',
                 'defensive_contribution': 1,
                 'element': 430,
                 'expected_assists': '0.00',
                 'expected_goal_involvements': '1.40',
                 'expected_goals': '1.40',
                 'expected_goals_conceded': '2.30',
                 'fixture': 22,
                 'goals_conceded': 2,
                 'goals_scored': 1,
                 'ict_index': '12.7',
                 'influence': '30.4',
                 'kickoff_time': '2025-08-31T13:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 6,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 1,
                 'red_cards': 0,
                 'round': 3,
                 'saves': 0,
                 'selected': 3747441,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 2,
                 'threat': '96.0',
                 'total_points': 9,
                 'transfers_balance': 179096,
                 'transfers_in': 366370,
                 'transfers_out': 187274,
                 'value': 141,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 63,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 6,
                 'creativity': '12.9',
                 'defensive_contribution': 8,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '1.81',
                 'expected_goals': '1.80',
                 'expected_goals_conceded': '1.42',
                 'fixture': 38,
                 'goals_conceded': 0,
                 'goals_scored': 2,
                 'ict_index': '16.2',
                 'influence': '78.8',
                 'kickoff_time': '2025-09-14T15:30:00Z',
                 'minutes': 86,
                 'modified': False,
                 'opponent_team': 14,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 2,
                 'red_cards': 0,
                 'round': 4,
                 'saves': 0,
                 'selected': 3931425,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 0,
                 'team_h_score': 3,
                 'threat': '70.0',
                 'total_points': 13,
                 'transfers_balance': 209666,
                 'transfers_in': 435454,
                 'transfers_out': 225788,
                 'value': 141,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 32,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '2.1',
                 'defensive_contribution': 5,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '0.53',
                 'expected_goals': '0.52',
                 'expected_goals_conceded': '0.77',
                 'fixture': 41,
                 'goals_conceded': 0,
                 'goals_scored': 1,
                 'ict_index': '7.2',
                 'influence': '35.4',
                 'kickoff_time': '2025-09-21T15:30:00Z',
                 'minutes': 75,
                 'modified': False,
                 'opponent_team': 1,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 3,
                 'red_cards': 0,
                 'round': 5,
                 'saves': 0,
                 'selected': 4419019,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 1,
                 'threat': '34.0',
                 'total_points': 9,
                 'transfers_balance': 405468,
                 'transfers_in': 479550,
                 'transfers_out': 74082,
                 'value': 142,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 1,
                 'bonus': 3,
                 'bps': 68,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '20.8',
                 'defensive_contribution': 4,
                 'element': 430,
                 'expected_assists': '0.24',
                 'expected_goal_involvements': '1.41',
                 'expected_goals': '1.17',
                 'expected_goals_conceded': '0.41',
                 'fixture': 57,
                 'goals_conceded': 1,
                 'goals_scored': 2,
                 'ict_index': '18.4',
                 'influence': '85.4',
                 'kickoff_time': '2025-09-27T14:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 3,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 2,
                 'red_cards': 0,
                 'round': 6,
                 'saves': 0,
                 'selected': 5991428,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 5,
                 'threat': '78.0',
                 'total_points': 16,
                 'transfers_balance': 1415070,
                 'transfers_in': 1490551,
                 'transfers_out': 75481,
                 'value': 143,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 2,
                 'bps': 36,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '3.4',
                 'defensive_contribution': 2,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '0.30',
                 'expected_goals': '0.29',
                 'expected_goals_conceded': '0.83',
                 'fixture': 64,
                 'goals_conceded': 0,
                 'goals_scored': 1,
                 'ict_index': '6.2',
                 'influence': '35.4',
                 'kickoff_time': '2025-10-05T15:30:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 5,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 0,
                 'red_cards': 0,
                 'round': 7,
                 'saves': 0,
                 'selected': 7060510,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 0,
                 'threat': '23.0',
                 'total_points': 8,
                 'transfers_balance': 1031965,
                 'transfers_in': 1038671,
                 'transfers_out': 6706,
                 'value': 144,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 62,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 2,
                 'creativity': '1.9',
                 'defensive_contribution': 4,
                 'element': 430,
                 'expected_assists': '0.02',
                 'expected_goal_involvements': '1.00',
                 'expected_goals': '0.98',
                 'expected_goals_conceded': '0.81',
                 'fixture': 76,
                 'goals_conceded': 0,
                 'goals_scored': 2,
                 'ict_index': '16.4',
                 'influence': '77.4',
                 'kickoff_time': '2025-10-18T14:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 9,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 2,
                 'red_cards': 0,
                 'round': 8,
                 'saves': 0,
                 'selected': 7826831,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 0,
                 'team_h_score': 2,
                 'threat': '85.0',
                 'total_points': 13,
                 'transfers_balance': 707569,
                 'transfers_in': 717731,
                 'transfers_out': 10162,
                 'value': 146,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 0,
                 'bps': 9,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 3,
                 'creativity': '2.6',
                 'defensive_contribution': 3,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '0.24',
                 'expected_goals': '0.23',
                 'expected_goals_conceded': '0.81',
                 'fixture': 82,
                 'goals_conceded': 1,
                 'goals_scored': 0,
                 'ict_index': '7.1',
                 'influence': '15.2',
                 'kickoff_time': '2025-10-26T14:00:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 2,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 0,
                 'red_cards': 0,
                 'round': 9,
                 'saves': 0,
                 'selected': 8327859,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 0,
                 'team_h_score': 1,
                 'threat': '53.0',
                 'total_points': 2,
                 'transfers_balance': 470274,
                 'transfers_in': 478726,
                 'transfers_out': 8452,
                 'value': 147,
                 'was_home': False,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 3,
                 'bps': 62,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 1,
                 'creativity': '3.8',
                 'defensive_contribution': 1,
                 'element': 430,
                 'expected_assists': '0.01',
                 'expected_goal_involvements': '1.34',
                 'expected_goals': '1.33',
                 'expected_goals_conceded': '0.71',
                 'fixture': 96,
                 'goals_conceded': 1,
                 'goals_scored': 2,
                 'ict_index': '15.7',
                 'influence': '71.6',
                 'kickoff_time': '2025-11-02T16:30:00Z',
                 'minutes': 81,
                 'modified': False,
                 'opponent_team': 4,
                 'own_goals': 0,
                 'penalties_missed': 0,
                 'penalties_saved': 0,
                 'recoveries': 0,
                 'red_cards': 0,
                 'round': 10,
                 'saves': 0,
                 'selected': 8565665,
                 'starts': 1,
                 'tackles': 0,
                 'team_a_score': 1,
                 'team_h_score': 3,
                 'threat': '82.0',
                 'total_points': 13,
                 'transfers_balance': 202821,
                 'transfers_in': 228200,
                 'transfers_out': 25379,
                 'value': 148,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 0,
                 'bps': 28,
                 'clean_sheets': 1,
                 'clearances_blocks_interceptions': 1,
                 'creativity': '1.6',
                 'defensive_contribution': 2,
                 'element': 430,
                 'expected_assists': '0.09',
                 'expected_goal_involvements': '0.94',
                 'expected_goals': '0.85',
                 'expected_goals_conceded': '0.71',
                 'fixture': 106,
                 'goals_conceded': 0,
                 'goals_scored': 1,
                 'ict_index': '8.1',
                 'influence': '37.0',
                 'kickoff_time': '2025-11-09T16:30:00Z',
                 'minutes': 90,
                 'modified': False,
                 'opponent_team': 12,
                 'own_goals': 0,
                 'penalties_missed': 1,
                 'penalties_saved': 0,
                 'recoveries': 0,
                 'red_cards': 0,
                 'round': 11,
                 'saves': 0,
                 'selected': 8719190,
                 'starts': 1,
                 'tackles': 1,
                 'team_a_score': 0,
                 'team_h_score': 3,
                 'threat': '42.0',
                 'total_points': 4,
                 'transfers_balance': 120567,
                 'transfers_in': 148317,
                 'transfers_out': 27750,
                 'value': 148,
                 'was_home': True,
                 'yellow_cards': 0},
               { 'assists': 0,
                 'bonus': 0,
                 'bps': 2,
                 'clean_sheets': 0,
                 'clearances_blocks_interceptions': 1,
                 'creativity': '1.3',
                 'defensive_contribution': 3,
                 'element': 430,

In [17]:
df_history = pd.json_normalize(data['history'])
df_history.head()

,element,fixture,opponent_team,total_points,was_home,kickoff_time,team_h_score,team_a_score,round,modified,...,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,value,transfers_balance,selected,transfers_in,transfers_out
0,430,7,20,13,False,2025-08-16T16:30:00Z,0,4,1,False,...,1,1.99,0.00,1.99,0.35,140,0,2283987,0,0
1,430,18,18,2,True,2025-08-23T11:30:00Z,0,2,2,False,...,1,0.47,0.30,0.77,1.11,140,396573,3276879,446334,49761
2,430,22,6,9,False,2025-08-31T13:00:00Z,2,1,3,False,...,1,1.40,0.00,1.40,2.30,141,179096,3747441,366370,187274
3,430,38,14,13,True,2025-09-14T15:30:00Z,3,0,4,False,...,1,1.80,0.01,1.81,1.42,141,209666,3931425,435454,225788
4,430,41,1,9,False,2025-09-21T15:30:00Z,1,1,5,False,...,1,0.52,0.01,0.53,0.77,142,405468,4419019,479550,74082

In [18]:
data = get_json_data('event/1/live')
pprint(data, indent=2)

<Response [200]>
{ 'elements': [ { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 90},
                                            { 'identifier': 'clean_sheets',
                                              'points': 4,
                                              'points_modification': 0,
                                              'value': 1},
                                            { 'identifier': 'yellow_cards',
                                              'points': -1,
                                              'points_modification': 0,
                                              'value': 1},
                                            { 'identifier': 'saves',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 7},
                                            { 'identifier': 'bonus',
                                              'points': 3,
                                              'points_modification': 0,
                                              'value': 3}]}],
                  'id': 1,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 3,
                             'bps': 38,
                             'clean_sheets': 1,
                             'clearances_blocks_interceptions': 1,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '1.52',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '4.9',
                             'in_dreamteam': True,
                             'influence': '49.2',
                             'minutes': 90,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 13,
                             'red_cards': 0,
                             'saves': 7,
                             'starts': 1,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 10,
                             'yellow_cards': 1}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 2,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 3,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 4,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 90},
                                            { 'identifier': 'clean_sheets',
                                              'points': 4,
                                              'points_modification': 0,
                                              'value': 1}]}],
                  'id': 5,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 23,
                             'clean_sheets': 1,
                             'clearances_blocks_interceptions': 6,
                             'creativity': '0.3',
                             'defensive_contribution': 7,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '1.52',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '2.7',
                             'in_dreamteam': False,
                             'influence': '22.8',
                             'minutes': 90,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 1,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 1,
                             'tackles': 1,
                             'threat': '4.0',
                             'total_points': 6,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 90},
                                            { 'identifier': 'clean_sheets',
                                              'points': 4,
                                              'points_modification': 0,
                                              'value': 1},
                                            { 'identifier': 'bonus',
                                              'points': 1,
                                              'points_modification': 0,
                                              'value': 1},
                                            { 'identifier': 'defensive_contribution',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 14}]}],
                  'id': 6,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 1,
                             'bps': 25,
                             'clean_sheets': 1,
                             'clearances_blocks_interceptions': 10,
                             'creativity': '0.1',
                             'defensive_contribution': 14,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '1.52',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '3.2',
                             'in_dreamteam': False,
                             'influence': '31.4',
                             'minutes': 90,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 3,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 1,
                             'tackles': 4,
                             'threat': '0.0',
                             'total_points': 9,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 71},
                                            { 'identifier': 'goals_scored',
                                              'points': 6,
                                              'points_modification': 0,
                                              'value': 1},
                                            { 'identifier': 'clean_sheets',
                                              'points': 4,
                                              'points_modification': 0,
                                              'value': 1},
                                            { 'identifier': 'yellow_cards',
                                              'points': -1,
                                              'points_modification': 0,
                                              'value': 1},
                                            { 'identifier': 'bonus',
                                              'points': 2,
                                              'points_modification': 0,
                                              'value': 2}]}],
                  'id': 7,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 2,
                             'bps': 33,
                             'clean_sheets': 1,
                             'clearances_blocks_interceptions': 3,
                             'creativity': '2.1',
                             'defensive_contribution': 4,
                             'expected_assists': '0.01',
                             'expected_goal_involvements': '0.92',
                             'expected_goals': '0.91',
                             'expected_goals_conceded': '0.87',
                             'goals_conceded': 0,
                             'goals_scored': 1,
                             'ict_index': '7.3',
                             'in_dreamteam': True,
                             'influence': '36.2',
                             'minutes': 71,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 5,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 1,
                             'tackles': 1,
                             'threat': '35.0',
                             'total_points': 13,
                             'yellow_cards': 1}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 1,
                                              'points_modification': 0,
                                              'value': 19},
                                            { 'identifier': 'yellow_cards',
                                              'points': -1,
                                              'points_modification': 0,
                                              'value': 1}]}],
                  'id': 8,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': -3,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 1,
                             'creativity': '0.3',
                             'defensive_contribution': 3,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.66',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.3',
                             'in_dreamteam': False,
                             'influence': '3.0',
                             'minutes': 19,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 1,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 2,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 1}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 0,
                                              'points_modification': 0,
                                              'value': 0}]}],
                  'id': 9,
                  'modified': False,
                  'stats': { 'assists': 0,
                             'bonus': 0,
                             'bps': 0,
                             'clean_sheets': 0,
                             'clearances_blocks_interceptions': 0,
                             'creativity': '0.0',
                             'defensive_contribution': 0,
                             'expected_assists': '0.00',
                             'expected_goal_involvements': '0.00',
                             'expected_goals': '0.00',
                             'expected_goals_conceded': '0.00',
                             'goals_conceded': 0,
                             'goals_scored': 0,
                             'ict_index': '0.0',
                             'in_dreamteam': False,
                             'influence': '0.0',
                             'minutes': 0,
                             'own_goals': 0,
                             'penalties_missed': 0,
                             'penalties_saved': 0,
                             'recoveries': 0,
                             'red_cards': 0,
                             'saves': 0,
                             'starts': 0,
                             'tackles': 0,
                             'threat': '0.0',
                             'total_points': 0,
                             'yellow_cards': 0}},
                { 'explain': [ { 'fixture': 9,
                                 'stats': [ { 'identifier': 'minutes',
                                              'points': 1,
                                              'points_modification': 0,
                                              'value': 18},
                                            { 'identifier': 'yellow_cards',
                                              'points': -1,
                                              'points_modification': 0,
                                              'value': 1}]}],
                  'id': 10,

In [19]:
data = get_json_data('fixtures')
pprint(data, indent=2)

<Response [200]>
[ { 'code': 2561895,
    'event': 1,
    'finished': True,
    'finished_provisional': True,
    'id': 1,
    'kickoff_time': '2025-08-15T19:00:00Z',
    'minutes': 90,
    'provisional_start_time': False,
    'pulse_id': 124791,
    'started': True,
    'stats': [ { 'a': [{'element': 82, 'value': 2}],
                 'h': [ {'element': 381, 'value': 1},
                        {'element': 384, 'value': 1},
                        {'element': 385, 'value': 1},
                        {'element': 661, 'value': 1}],
                 'identifier': 'goals_scored'},
               { 'a': [ {'element': 86, 'value': 1},
                        {'element': 93, 'value': 1}],
                 'h': [ {'element': 386, 'value': 1},
                        {'element': 392, 'value': 1},
                        {'element': 661, 'value': 1}],
                 'identifier': 'assists'},
               {'a': [], 'h': [], 'identifier': 'own_goals'},
               {'a': [], 'h': [], 'identifier': 'penalties_saved'},
               {'a': [], 'h': [], 'identifier': 'penalties_missed'},
               { 'a': [ {'element': 86, 'value': 1},
                        {'element': 97, 'value': 1}],
                 'h': [{'element': 371, 'value': 1}],
                 'identifier': 'yellow_cards'},
               {'a': [], 'h': [], 'identifier': 'red_cards'},
               { 'a': [{'element': 67, 'value': 6}],
                 'h': [{'element': 366, 'value': 1}],
                 'identifier': 'saves'},
               { 'a': [{'element': 82, 'value': 3}],
                 'h': [ {'element': 661, 'value': 2},
                        {'element': 381, 'value': 1}],
                 'identifier': 'bonus'},
               { 'a': [ {'element': 82, 'value': 42},
                        {'element': 86, 'value': 23},
                        {'element': 84, 'value': 20},
                        {'element': 93, 'value': 12},
                        {'element': 85, 'value': 11},
                        {'element': 67, 'value': 10},
                        {'element': 90, 'value': 7},
                        {'element': 96, 'value': 3},
                        {'element': 73, 'value': 2},
                        {'element': 100, 'value': 2},
                        {'element': 685, 'value': 2},
                        {'element': 72, 'value': 1},
                        {'element': 74, 'value': -1},
                        {'element': 97, 'value': -1}],
                 'h': [ {'element': 661, 'value': 37},
                        {'element': 381, 'value': 36},
                        {'element': 384, 'value': 34},
                        {'element': 385, 'value': 29},
                        {'element': 386, 'value': 27},
                        {'element': 387, 'value': 17},
                        {'element': 392, 'value': 15},
                        {'element': 382, 'value': 14},
                        {'element': 373, 'value': 11},
                        {'element': 366, 'value': 8},
                        {'element': 370, 'value': 8},
                        {'element': 374, 'value': 6},
                        {'element': 371, 'value': 5},
                        {'element': 388, 'value': 4},
                        {'element': 376, 'value': -1},
                        {'element': 372, 'value': -3}],
                 'identifier': 'bps'},
               { 'a': [ {'element': 84, 'value': 20},
                        {'element': 85, 'value': 19},
                        {'element': 72, 'value': 15},
                        {'element': 73, 'value': 9},
                        {'element': 685, 'value': 9},
                        {'element': 86, 'value': 7},
                        {'element': 74, 'value': 6},
                        {'element': 82, 'value': 5},
                        {'element': 97, 'value': 5},
                        {'element': 93, 'value': 4},
                        {'element': 90, 'value': 3},
                        {'element': 77, 'value': 2}],
                 'h': [ {'element': 373, 'value': 21},
                        {'element': 387, 'value': 11},
                        {'element': 381, 'value': 10},
                        {'element': 382, 'value': 9},
                        {'element': 384, 'value': 8},
                        {'element': 374, 'value': 7},
                        {'element': 371, 'value': 6},
                        {'element': 386, 'value': 6},
                        {'element': 370, 'value': 4},
                        {'element': 392, 'value': 3},
                        {'element': 372, 'value': 2},
                        {'element': 376, 'value': 1},
                        {'element': 385, 'value': 1},
                        {'element': 388, 'value': 1},
                        {'element': 661, 'value': 1}],
                 'identifier': 'defensive_contribution'}],
    'team_a': 4,
    'team_a_difficulty': 4,
    'team_a_score': 2,
    'team_h': 12,
    'team_h_difficulty': 3,
    'team_h_score': 4},
  { 'code': 2561896,
    'event': 1,
    'finished': True,
    'finished_provisional': True,
    'id': 2,
    'kickoff_time': '2025-08-16T11:30:00Z',
    'minutes': 90,
    'provisional_start_time': False,
    'pulse_id': 124792,
    'started': True,
    'stats': [ {'a': [], 'h': [], 'identifier': 'goals_scored'},
               {'a': [], 'h': [], 'identifier': 'assists'},
               {'a': [], 'h': [], 'identifier': 'own_goals'},
               {'a': [], 'h': [], 'identifier': 'penalties_saved'},
               {'a': [], 'h': [], 'identifier': 'penalties_missed'},
               { 'a': [{'element': 490, 'value': 1}],
                 'h': [{'element': 58, 'value': 1}],
                 'identifier': 'yellow_cards'},
               { 'a': [],
                 'h': [{'element': 38, 'value': 1}],
                 'identifier': 'red_cards'},
               { 'a': [{'element': 469, 'value': 3}],
                 'h': [{'element': 33, 'value': 3}],
                 'identifier': 'saves'},
               { 'a': [ {'element': 477, 'value': 3},
                        {'element': 469, 'value': 2},
                        {'element': 476, 'value': 1}],
                 'h': [],
                 'identifier': 'bonus'},
               { 'a': [ {'element': 477, 'value': 33},
                        {'element': 469, 'value': 32},
                        {'element': 476, 'value': 30},
                        {'element': 474, 'value': 26},
                        {'element': 478, 'value': 26},
                        {'element': 491, 'value': 20},
                        {'element': 487, 'value': 15},
                        {'element': 488, 'value': 11},
                        {'element': 486, 'value': 10},
                        {'element': 490, 'value': 7},
                        {'element': 485, 'value': 4},
                        {'element': 497, 'value': 4},
                        {'element': 489, 'value': 3},
                        {'element': 500, 'value': 3}],
                 'h': [ {'element': 33, 'value': 29},
                        {'element': 36, 'value': 25},
                        {'element': 40, 'value': 25},
                        {'element': 37, 'value': 22},
                        {'element': 59, 'value': 19},
                        {'element': 38, 'value': 15},
                        {'element': 58, 'value': 13},
                        {'element': 64, 'value': 12},
                        {'element': 54, 'value': 10},
                        {'element': 47, 'value': 7},
                        {'element': 48, 'value': 5},
                        {'element': 53, 'value': 4}],
                 'identifier': 'bps'},
               { 'a': [ {'element': 474, 'value': 11},
                        {'element': 476, 'value': 11},
                        {'element': 490, 'value': 9},
                        {'element': 491, 'value': 9},
                        {'element': 488, 'value': 8},
                        {'element': 477, 'value': 5},
                        {'element': 478, 'value': 4},
                        {'element': 485, 'value': 4},
                        {'element': 487, 'value': 4},
                        {'element': 486, 'value': 3},
                        {'element': 489, 'value': 2},
                        {'element': 497, 'value': 1}],
                 'h': [ {'element': 59, 'value': 14},
                        {'element': 36, 'value': 11},
                        {'element': 58, 'value': 11},
                        {'element': 37, 'value': 7},
                        {'element': 47, 'value': 7},
                        {'element': 48, 'value': 7},
                        {'element': 54, 'value': 7},
                        {'element': 40, 'value': 5},
                        {'element': 64, 'value': 5},
                        {'element': 38, 'value': 3}],
                 'identifier': 'defensive_contribution'}],
    'team_a': 15,
    'team_a_difficulty': 4,
    'team_a_score': 0,
    'team_h': 2,
    'team_h_difficulty': 3,
    'team_h_score': 0},
  { 'code': 2561897,
    'event': 1,
    'finished': True,
    'finished_provisional': True,
    'id': 3,
    'kickoff_time': '2025-08-16T14:00:00Z',
    'minutes': 90,
    'provisional_start_time': False,
    'pulse_id': 124793,
    'started': True,
    'stats': [ { 'a': [{'element': 338, 'value': 1}],
                 'h': [{'element': 164, 'value': 1}],
                 'identifier': 'goals_scored'},
               { 'a': [{'element': 329, 'value': 1}],
                 'h': [{'element': 158, 'value': 1}],
                 'identifier': 'assists'},
               {'a': [], 'h': [], 'identifier': 'own_goals'},
               {'a': [], 'h': [], 'identifier': 'penalties_saved'},
               {'a': [], 'h': [], 'identifier': 'penalties_missed'},
               { 'a': [ {'element': 318, 'value': 1},
                        {'element': 331, 'value': 1},
                        {'element': 338, 'value': 1}],
                 'h': [ {'element': 148, 'value': 1},
                        {'element': 157, 'value': 1},
                        {'element': 169, 'value': 1}],
                 'identifier': 'yellow_cards'},
               {'a': [], 'h': [], 'identifier': 'red_cards'},
               { 'a': [{'element': 314, 'value': 3}],
                 'h': [{'element': 139, 'value': 1}],
                 'identifier': 'saves'},
               { 'a': [{'element': 338, 'value': 3}],
                 'h': [ {'element': 164, 'value': 2},
                        {'element': 166, 'value': 1}],
                 'identifier': 'bonus'},
               { 'a': [ {'element': 338, 'value': 25},
                        {'element': 322, 'value': 17},
                        {'element': 329, 'value': 16},
                        {'element': 314, 'value': 15},
                        {'element': 317, 'value': 14},
                        {'element': 335, 'value': 11},
                        {'element': 321, 'value': 10},
                        {'element': 324, 'value': 10},
                        {'element': 332, 'value': 9},
                        {'element': 318, 'value': 3},
                        {'element': 319, 'value': 3},
                        {'element': 330, 'value': 3},
                        {'element': 325, 'value': 2},
                        {'element': 326, 'value': 1},
                        {'element': 331, 'value': -3}],
                 'h': [ {'element': 164, 'value': 24},
                        {'element': 166, 'value': 20},
                        {'element': 173, 'value': 17},
                        {'element': 146, 'value': 16},
                        {'element': 151, 'value': 15},
                        {'element': 158, 'value': 15},
                        {'element': 167, 'value': 10},
                        {'element': 139, 'value': 9},
                        {'element': 145, 'value': 8},
                        {'element': 160, 'value': 7},
                        {'element': 169, 'value': 7},
                        {'element': 170, 'value': 3},
                        {'element': 178, 'value': 3},
                        {'element': 157, 'value': -2},
                        {'element': 162, 'value': -2},
                        {'element': 148, 'value': -5}],
                 'identifier': 'bps'},
               { 'a': [ {'element': 335, 'value': 9},
                        {'element': 317, 'value': 8},
                        {'element': 322, 'value': 7},
                        {'element': 329, 'value': 6},
                        {'element': 318, 'value': 4},
                        {'element': 321, 'value': 3},
                        {'element': 332, 'value': 3},
                        {'element': 324, 'value': 2},
                        {'element': 330, 'value': 2},
                        {'element': 331, 'value': 2}],
                 'h': [ {'element': 173, 'value': 18},
                        {'element': 167, 'value': 11},
                        {'element': 166, 'value': 10},
                        {'element': 146, 'value': 8},
                        {'element': 151, 'value': 8},
                        {'element': 145, 'value': 6},
                        {'element': 169, 'value': 5},
                        {'element': 160, 'value': 4},
                        {'element': 164, 'value': 3},
                        {'element': 158, 'value': 2},
                        {'element': 162, 'value': 2},
                        {'element': 148, 'value': 1},
                        {'element': 178, 'value': 1}],
                 'identifier': 'defensive_contribution'}],
    'team_a': 10,
    'team_a_difficulty': 4,
    'team_a_score': 1,
    'team_h': 6,
    'team_h_difficulty': 3,
    'team_h_score': 1},
  { 'code': 2561900,
    'event': 1,
    'finished': True,
    'finished_provisional': True,
    'id': 6,
    'kickoff_time': '2025-08-16T14:00:00Z',
    'minutes': 90,
    'provisional_start_time': False,
    'pulse_id': 124796,
    'started': True,
    'stats': [ { 'a': [],
                 'h': [ {'element': 597, 'value': 2},
                        {'element': 580, 'value': 1}],
                 'identifier': 'goals_scored'},
               { 'a': [],
                 'h': [ {'element': 582, 'value': 2},
                        {'element': 593, 'value': 1}],
                 'identifier': 'assists'},
               {'a': [], 'h': [], 'identifier': 'own_goals'},
               {'a': [], 'h': [], 'identifier': 'penalties_saved'},
               {'a': [], 'h': [], 'identifier': 'penalties_missed'},
               {'a': [], 'h': [], 'identifier': 'yellow_cards'},
               {'a': [], 'h': [], 'identifier': 'red_cards'},
               { 'a': [{'element': 470, 'value': 3}],
                 'h': [{'element': 565, 'value': 4}],
                 'identifier': 'saves'},
               { 'a': [],
                 'h': [ {'element': 597, 'value': 3},
                        {'element': 565, 'value': 2},
                        {'element': 582, 'value': 1}],
                 'identifier': 'bonus'},
               { 'a': [ {'element': 205, 'value': 21},
                        {'element': 209, 'value': 11},
                        {'element': 200, 'value': 9},
                        {'element': 207, 'value': 8},
                        {'element': 217, 'value': 6},
                        {'element': 470, 'value': 5},
                        {'element': 210, 'value': 4},
                        {'element': 206, 'value': 3},
                        {'element': 215, 'value': 3},
                        {'element': 202, 'value': 2},
                        {'element': 676, 'value': 1},
                        {'element': 192, 'value': -2},
                        {'element': 187, 'value': -3},
                        {'element': 197, 'value': -4},
                        {'element': 190, 'value': -5}],
                 'h': [ {'element': 597, 'value': 61},
                        {'element': 565, 'value': 36},
                        {'element': 582, 'value': 35},
                        {'element': 580, 'value': 30},
                        {'element': 593, 'value': 29},
                        {'element': 575, 'value': 27},
                        {'element': 568, 'value': 26},
                        {'element': 573, 'value': 26},
                        {'element': 569, 'value': 22},
                        {'element': 586, 'value': 13},
                        {'element': 591, 'value': 13},
                        {'element': 585, 'value': 5},
                        {'element': 596, 'value': 5},
                        {'element': 588, 'value': 4},
                        {'element': 673, 'value': 2},
                        {'element': 584, 'value': 1}],
                 'identifier': 'bps'},
               { 'a': [ {'element': 205, 'value': 12},
                        {'element': 191, 'value': 8},
                        {'element': 192, 'value': 6},
                        {'element': 209, 'value': 6},
                        {'element': 187, 'value': 5},
                        {'element': 190, 'value': 5},
                        {'element': 200, 'value': 4},
                        {'element': 217, 'value': 3},
                        {'element': 202, 'value': 2},
                        {'element': 210, 'value': 2},
                        {'element': 207, 'value': 1},
                        {'element': 676, 'value': 1}],
                 'h': [ {'element': 593, 'value': 10},
                        {'element': 591, 'value': 8},
                        {'element': 575, 'value': 6},
                        {'element': 569, 'value': 5},
                        {'element': 597, 'value': 5},
                        {'element': 568, 'value': 4},
                        {'element': 582, 'value': 4},
                        {'element': 586, 'value': 4},
                        {'element': 573, 'value': 3},
                        {'element': 580, 'value': 3},
                        {'element': 585, 'value': 3},
                        {'element': 596, 'value': 2},
                        {'element': 588, 'value': 1}],
                 'identifier': 'defensive_contribution'}],
    'team_a': 3,
    'team_a_difficulty': 3,
    'team_a_score': 0,
    'team_h': 18,
    'team_h_difficulty': 1,
    'team_h_score': 3},
  { 'code': 2561899,
    'event': 1,
    'finished': True,
    'finished_provisional': True,
    'id': 5,
    'kickoff_time': '2025-08-16T14:00:00Z',
    'minutes': 90,
    'provisional_start_time': False,
    'pulse_id': 124795,
    'started': True,
    'stats': [ { 'a': [],
                 'h': [ {'element': 531, 'value': 1},
                        {'element': 560, 'value': 1},
                        {'element': 561, 'value': 1}],
                 'identifier': 'goals_scored'},
               { 'a': [],
                 'h': [ {'element': 543, 'value': 1},
                        {'element': 553, 'value': 1},
                        {'element': 683, 'value': 1}],
                 'identifier': 'assists'},
               {'a': [], 'h': [], 'identifier': 'own_goals'},
               {'a': [], 'h': [], 'identifier': 'penalties_saved'},
               {'a': [], 'h': [], 'identifier': 'penalties_missed'},
               { 'a': [{'element': 605, 'value': 1}],
                 'h': [],
                 'identifier': 'yellow_cards'},
               {'a': [], 'h': [], 'identifier': 'red_cards'},
               { 'a': [{'element': 679, 'value': 2}],
                 'h': [{'element': 670, 'value': 4}],
                 'identifier': 'saves'},
               { 'a': [],
                 'h': [ {'element': 531, 'value': 3},
                        {'element': 561, 'value': 2},
                        {'element': 670, 'value': 1}],
                 'identifier': 'bonus'},
               { 'a': [ {'element': 614, 'value': 13},

In [20]:
!pip install understatapi pandas

Collecting understatapi
  Downloading understatapi-0.7.1.tar.gz (537 kB)
     ---------------------------------------- 0.0/537.7 kB ? eta -:--:--
     ---------------------------------------- 537.7/537.7 kB 7.5 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: pandas in c:\users\alecw\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: certifi==2025.11.12 in c:\users\alecw\anaconda3\lib\site-packages (from understatapi) (2025.11.12)
Requirement already satisfied: charset-normalizer==3.4.4 in c:\users\alecw\anaconda3\lib\site-packages (from understatapi) (3.4.4)
Collecting idna==2.10 (from understatapi)
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Requirement already satisfied: requests==2.32.5 in c:\users\alecw\anaconda3\lib\site-packages (from understatapi) (2.32.5)
Collecting urllib3==1.26.5 (from understatapi)
  Downloading urllib3-1.26.5-py2.py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\alecw\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alecw\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alecw\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alecw\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\alecw\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Downloading urllib3-1.26.5-py2.py3-none-any.whl (138 kB)
Building wheels for collected packages: understatapi
  Building wheel for understatapi (pyproject.toml): started
  Building wheel for understatapi (pyproject.toml): finished with status 'done'
  Created wheel for understatapi: filename=understatapi-0.7.1-py3-none-any.whl size=15474 sha256=debe382541fcd98882fd1b1789b4392cb5c1168b4972a1e4f8b54646628f8504
  Stored in directory: c:\users\alecw\appdata\local\pip\cache\wheels\29\80\82\06d77c7a1324f1db92640d5af17ed2423b1d2c4b3dcedc7aea
Successfully built understatapi
Installing collected packages: urllib3, idna, understatapi

  Attempting uninstall: urllib3

    Found existing installation: urllib3 2.5.0

    Uninstalling urllib3-2.5.0:

      Successfully uninstalled urllib3-2.5.0

   ---------------------------------------- 0/3 [urllib3]
  Attempting uninstall: idna
   ---------------------------------------- 0/3 [urllib3]
    Found existing installation: idna 3.11
   ---------------------------------------- 0/3 [urllib3]
    Uninstalling idna-3.11:
   ---------------------------------------- 0/3 [urllib3]
      Successfully uninstalled idna-3.11
   ---------------------------------------- 0/3 [urllib3]
   ------------- -------------------------- 1/3 [idna]
   ---------------------------------------- 3/3 [understatapi]

Successfully installed idna-2.10 understatapi-0.7.1 urllib3-1.26.5

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda-repo-cli 1.0.173 requires urllib3>=2.2.2, but you have urllib3 1.26.5 which is incompatible.
sentry-sdk 2.45.0 requires urllib3>=1.26.11, but you have urllib3 1.26.5 which is incompatible.

In [21]:
import understatapi

client = understatapi.UnderstatClient()

In [36]:
league_data = client.league(league='EPL').get_match_data(season='2016')

In [37]:
league_data

[{'id': '461',
  'isResult': True,
  'h': {'id': '91', 'title': 'Hull', 'short_title': 'HUL'},
  'a': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '0.740018', 'a': '2.45631'},
  'datetime': '2016-08-13 15:30:00',
  'forecast': {'w': '0.0538', 'd': '0.1247', 'l': '0.8215'}},
 {'id': '462',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '76', 'title': 'West Bromwich Albion', 'short_title': 'WBA'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '0.990062', 'a': '0.684593'},
  'datetime': '2016-08-13 18:00:00',
  'forecast': {'w': '0.4295', 'd': '0.3356', 'l': '0.2349'}},
 {'id': '463',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.790063', 'a': '1.12348'},
  'datetime': '2016-08-13 18:00:00',
  'forecast': {'w': '0.2313', 'd': '0.3322', 'l': '0.4365'}},
 {'id': '464',
  'isResult': True,
  'h': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'a': {'id': '84', 'title': 'Swansea', 'short_title': 'SWA'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '1.04903', 'a': '1.72089'},
  'datetime': '2016-08-13 18:00:00',
  'forecast': {'w': '0.1626', 'd': '0.2888', 'l': '0.5486'}},
 {'id': '465',
  'isResult': True,
  'h': {'id': '93', 'title': 'Middlesbrough', 'short_title': 'MID'},
  'a': {'id': '85', 'title': 'Stoke', 'short_title': 'STO'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '1.80523', 'a': '0.485626'},
  'datetime': '2016-08-13 18:00:00',
  'forecast': {'w': '0.7885', 'd': '0.1624', 'l': '0.0491'}},
 {'id': '466',
  'isResult': True,
  'h': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'a': {'id': '90', 'title': 'Watford', 'short_title': 'WAT'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.937328', 'a': '0.180046'},
  'datetime': '2016-08-13 18:00:00',
  'forecast': {'w': '0.5425', 'd': '0.3917', 'l': '0.0658'}},
 {'id': '467',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.95479', 'a': '1.09877'},
  'datetime': '2016-08-13 20:30:00',
  'forecast': {'w': '0.598', 'd': '0.2506', 'l': '0.1514'}},
 {'id': '468',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '1', 'a': '3'},
  'xG': {'h': '0.522847', 'a': '1.91105'},
  'datetime': '2016-08-14 16:30:00',
  'forecast': {'w': '0.0548', 'd': '0.159', 'l': '0.7862'}},
 {'id': '469',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '3', 'a': '4'},
  'xG': {'h': '1.18197', 'a': '1.6591'},
  'datetime': '2016-08-14 19:00:00',
  'forecast': {'w': '0.2393', 'd': '0.2859', 'l': '0.4748'}},
 {'id': '470',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.4603', 'a': '0.445604'},
  'datetime': '2016-08-15 23:00:00',
  'forecast': {'w': '0.6858', 'd': '0.2362', 'l': '0.078'}},
 {'id': '471',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'goals': {'h': '2', 'a': '0'},
  'xG': {'h': '1.36553', 'a': '0.613233'},
  'datetime': '2016-08-19 23:00:00',
  'forecast': {'w': '0.6019', 'd': '0.2712', 'l': '0.1269'}},
 {'id': '472',
  'isResult': True,
  'h': {'id': '85', 'title': 'Stoke', 'short_title': 'STO'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '1', 'a': '4'},
  'xG': {'h': '1.31066', 'a': '2.17198'},
  'datetime': '2016-08-20 15:30:00',
  'forecast': {'w': '0.1427', 'd': '0.2554', 'l': '0.6019'}},
 {'id': '473',
  'isResult': True,
  'h': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '2', 'a': '0'},
  'xG': {'h': '0.197536', 'a': '0.939025'},
  'datetime': '2016-08-20 18:00:00',
  'forecast': {'w': '0.0721', 'd': '0.373', 'l': '0.5549'}},
 {'id': '474',
  'isResult': True,
  'h': {'id': '84', 'title': 'Swansea', 'short_title': 'SWA'},
  'a': {'id': '91', 'title': 'Hull', 'short_title': 'HUL'},
  'goals': {'h': '0', 'a': '2'},
  'xG': {'h': '1.14134', 'a': '2.18655'},
  'datetime': '2016-08-20 18:00:00',
  'forecast': {'w': '0.135', 'd': '0.2041', 'l': '0.6609'}},
 {'id': '475',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '2.25623', 'a': '0.357943'},
  'datetime': '2016-08-20 18:00:00',
  'forecast': {'w': '0.8706', 'd': '0.1053', 'l': '0.0241'}},
 {'id': '476',
  'isResult': True,
  'h': {'id': '90', 'title': 'Watford', 'short_title': 'WAT'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '0.804549', 'a': '1.75595'},
  'datetime': '2016-08-20 18:00:00',
  'forecast': {'w': '0.1078', 'd': '0.2467', 'l': '0.6455'}},
 {'id': '477',
  'isResult': True,
  'h': {'id': '76', 'title': 'West Bromwich Albion', 'short_title': 'WBA'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '2.01885', 'a': '1.83897'},
  'datetime': '2016-08-20 18:00:00',
  'forecast': {'w': '0.3984', 'd': '0.2562', 'l': '0.3454'}},
 {'id': '478',
  'isResult': True,
  'h': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '0.553693', 'a': '0.521509'},
  'datetime': '2016-08-20 20:30:00',
  'forecast': {'w': '0.2918', 'd': '0.4486', 'l': '0.2596'}},
 {'id': '479',
  'isResult': True,
  'h': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'a': {'id': '93', 'title': 'Middlesbrough', 'short_title': 'MID'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '1.4645', 'a': '0.854908'},
  'datetime': '2016-08-21 16:30:00',
  'forecast': {'w': '0.5193', 'd': '0.2957', 'l': '0.185'}},
 {'id': '480',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '1.69288', 'a': '0.39341'},
  'datetime': '2016-08-21 19:00:00',
  'forecast': {'w': '0.7472', 'd': '0.1962', 'l': '0.0566'}},
 {'id': '481',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.590511', 'a': '1.92569'},
  'datetime': '2016-08-27 15:30:00',
  'forecast': {'w': '0.0672', 'd': '0.1704', 'l': '0.7624'}},
 {'id': '482',
  'isResult': True,
  'h': {'id': '90', 'title': 'Watford', 'short_title': 'WAT'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '1', 'a': '3'},
  'xG': {'h': '1.07775', 'a': '2.03271'},
  'datetime': '2016-08-27 18:00:00',
  'forecast': {'w': '0.1375', 'd': '0.2184', 'l': '0.6441'}},
 {'id': '483',
  'isResult': True,
  'h': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'a': {'id': '84', 'title': 'Swansea', 'short_title': 'SWA'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '2.47977', 'a': '0.32818'},
  'datetime': '2016-08-27 18:00:00',
  'forecast': {'w': '0.9129', 'd': '0.0717', 'l': '0.0154'}},
 {'id': '484',
  'isResult': True,
  'h': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'a': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.613743', 'a': '1.39142'},
  'datetime': '2016-08-27 18:00:00',
  'forecast': {'w': '0.1211', 'd': '0.2572', 'l': '0.6217'}},
 {'id': '485',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '2.65838', 'a': '0.18449'},
  'datetime': '2016-08-27 18:00:00',
  'forecast': {'w': '0.9265', 'd': '0.0623', 'l': '0.0112'}},
 {'id': '486',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '2.659', 'a': '0.974014'},
  'datetime': '2016-08-27 18:00:00',
  'forecast': {'w': '0.7804', 'd': '0.1446', 'l': '0.075'}},
 {'id': '487',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '85', 'title': 'Stoke', 'short_title': 'STO'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '2.31835', 'a': '0.187415'},
  'datetime': '2016-08-27 18:00:00',
  'forecast': {'w': '0.9114', 'd': '0.0778', 'l': '0.0108'}},
 {'id': '488',
  'isResult': True,
  'h': {'id': '91', 'title': 'Hull', 'short_title': 'HUL'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '0', 'a': '1'},
  'xG': {'h': '0.268815', 'a': '2.47208'},
  'datetime': '2016-08-27 20:30:00',
  'forecast': {'w': '0.0115', 'd': '0.0622', 'l': '0.9263'}},
 {'id': '489',
  'isResult': True,
  'h': {'id': '76', 'title': 'West Bromwich Albion', 'short_title': 'WBA'},
  'a': {'id': '93', 'title': 'Middlesbrough', 'short_title': 'MID'},
  'goals': {'h': '0', 'a': '0'},
  'xG': {'h': '0.696845', 'a': '0.396816'},
  'datetime': '2016-08-28 16:30:00',
  'forecast': {'w': '0.383', 'd': '0.4435', 'l': '0.1735'}},
 {'id': '490',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '3.21624', 'a': '1.08385'},
  'datetime': '2016-08-28 19:00:00',
  'forecast': {'w': '0.8305', 'd': '0.1137', 'l': '0.0558'}},
 {'id': '491',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '1.01013', 'a': '1.88688'},
  'datetime': '2016-09-10 15:30:00',
  'forecast': {'w': '0.1589', 'd': '0.2351', 'l': '0.606'}},
 {'id': '492',
  'isResult': True,
  'h': {'id': '93', 'title': 'Middlesbrough', 'short_title': 'MID'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '0.611959', 'a': '1.12437'},
  'datetime': '2016-09-10 18:00:00',
  'forecast': {'w': '0.1752', 'd': '0.317', 'l': '0.5078'}},
 {'id': '493',
  'isResult': True,
  'h': {'id': '85', 'title': 'Stoke', 'short_title': 'STO'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '0', 'a': '4'},
  'xG': {'h': '1.01771', 'a': '2.77025'},
  'datetime': '2016-09-10 18:00:00',
  'forecast': {'w': '0.0711', 'd': '0.1311', 'l': '0.7978'}},
 {'id': '494',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'goals': {'h': '2', 'a': '1'},
  'xG': {'h': '1.89219', 'a': '1.17522'},
  'datetime': '2016-09-10 18:00:00',
  'forecast': {'w': '0.5518', 'd': '0.2623', 'l': '0.1859'}},
 {'id': '495',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '76', 'title': 'West Bromwich Albion', 'short_title': 'WBA'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '0.986511', 'a': '1.48347'},
  'datetime': '2016-09-10 18:00:00',
  'forecast': {'w': '0.2038', 'd': '0.287', 'l': '0.5092'}},
 {'id': '496',
  'isResult': True,
  'h': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'a': {'id': '91', 'title': 'Hull', 'short_title': 'HUL'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.453149', 'a': '0.907116'},
  'datetime': '2016-09-10 18:00:00',
  'forecast': {'w': '0.1647', 'd': '0.3618', 'l': '0.4735'}},
 {'id': '497',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '90', 'title': 'Watford', 'short_title': 'WAT'},
  'goals': {'h': '2', 'a': '4'},
  'xG': {'h': '1.32216', 'a': '1.85479'},
  'datetime': '2016-09-10 18:00:00',
  'forecast': {'w': '0.2437', 'd': '0.2487', 'l': '0.5076'}},
 {'id': '498',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'goals': {'h': '4', 'a': '1'},
  'xG': {'h': '2.76916', 'a': '1.22508'},
  'datetime': '2016-09-10 20:30:00',
  'forecast': {'w': '0.7347', 'd': '0.1643', 'l': '0.101'}},
 {'id': '499',
  'isResult': True,
  'h': {'id': '84', 'title': 'Swansea', 'short_title': 'SWA'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '2', 'a': '2'},
  'xG': {'h': '1.2304', 'a': '2.19035'},
  'datetime': '2016-09-11 19:00:00',
  'forecast': {'w': '0.1643', 'd': '0.2464', 'l': '0.5893'}},
 {'id': '500',
  'isResult': True,
  'h': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '0', 'a': '3'},
  'xG': {'h': '1.0404', 'a': '2.84526'},
  'datetime': '2016-09-12 23:00:00',
  'forecast': {'w': '0.0753', 'd': '0.141', 'l': '0.7837'}},
 {'id': '501',
  'isResult': True,
  'h': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'a': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '1.16415', 'a': '1.41642'},
  'datetime': '2016-09-16 23:00:00',
  'forecast': {'w': '0.272', 'd': '0.3052', 'l': '0.4228'}},
 {'id': '502',
  'isResult': True,
  'h': {'id': '91', 'title': 'Hull', 'short_title': 'HUL'},
  'a': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'goals': {'h': '1', 'a': '4'},
  'xG': {'h': '0.969693', 'a': '3.63453'},
  'datetime': '2016-09-17 18:00:00',
  'forecast': {'w': '0.0142', 'd': '0.0649', 'l': '0.9209'}},
 {'id': '503',
  'isResult': True,
  'h': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'a': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '1.98503', 'a': '0.464523'},
  'datetime': '2016-09-17 18:00:00',
  'forecast': {'w': '0.8043', 'd': '0.155', 'l': '0.0407'}},
 {'id': '504',
  'isResult': True,
  'h': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'a': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'goals': {'h': '4', 'a': '0'},
  'xG': {'h': '3.38733', 'a': '0.389672'},
  'datetime': '2016-09-17 18:00:00',
  'forecast': {'w': '0.971', 'd': '0.0252', 'l': '0.0038'}},
 {'id': '505',
  'isResult': True,
  'h': {'id': '76', 'title': 'West Bromwich Albion', 'short_title': 'WBA'},
  'a': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'goals': {'h': '4', 'a': '2'},
  'xG': {'h': '1.94229', 'a': '2.37422'},
  'datetime': '2016-09-17 18:00:00',
  'forecast': {'w': '0.2819', 'd': '0.2606', 'l': '0.4575'}},
 {'id': '506',
  'isResult': True,
  'h': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'a': {'id': '93', 'title': 'Middlesbrough', 'short_title': 'MID'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '1.17467', 'a': '0.178081'},
  'datetime': '2016-09-17 20:30:00',
  'forecast': {'w': '0.6985', 'd': '0.2628', 'l': '0.0387'}},
 {'id': '507',
  'isResult': True,
  'h': {'id': '90', 'title': 'Watford', 'short_title': 'WAT'},
  'a': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'goals': {'h': '3', 'a': '1'},
  'xG': {'h': '1.74506', 'a': '1.41359'},
  'datetime': '2016-09-18 15:00:00',
  'forecast': {'w': '0.4477', 'd': '0.2906', 'l': '0.2617'}},
 {'id': '508',
  'isResult': True,
  'h': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'a': {'id': '85', 'title': 'Stoke', 'short_title': 'STO'},
  'goals': {'h': '4', 'a': '1'},
  'xG': {'h': '1.31366', 'a': '1.20308'},
  'datetime': '2016-09-18 17:15:00',
  'forecast': {'w': '0.3724', 'd': '0.3114', 'l': '0.3162'}},
 {'id': '509',
  'isResult': True,
  'h': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'a': {'id': '84', 'title': 'Swansea', 'short_title': 'SWA'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '2.15218', 'a': '0.490661'},
  'datetime': '2016-09-18 17:15:00',
  'forecast': {'w': '0.7973', 'd': '0.1491', 'l': '0.0536'}},
 {'id': '510',
  'isResult': True,
  'h': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'a': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '2.52591', 'a': '0.960821'},
  'datetime': '2016-09-18 19:30:00',
  'forecast': {'w': '0.7549', 'd': '0.1649', 'l': '0.0802'}},
 {'id': '515',
  'isResult': True,
  'h': {'id': '84', 'title': 'Swansea', 'short_title': 'SWA'},
  'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'},
  'goals': {'h': '1', 'a': '3'},
  'xG': {'h': '1.11096', 'a': '2.57704'},
  'datetime': '2016-09-24 15:00:00',
  'forecast': {'w': '0.0867', 'd': '0.1701', 'l': '0.7432'}},
 {'id': '511',
  'isResult': True,
  'h': {'id': '89', 'title': 'Manchester United', 'short_title': 'MUN'},
  'a': {'id': '75', 'title': 'Leicester', 'short_title': 'LEI'},
  'goals': {'h': '4', 'a': '1'},
  'xG': {'h': '2.45604', 'a': '0.286966'},
  'datetime': '2016-09-24 15:30:00',
  'forecast': {'w': '0.9268', 'd': '0.0632', 'l': '0.01'}},
 {'id': '512',
  'isResult': True,
  'h': {'id': '93', 'title': 'Middlesbrough', 'short_title': 'MID'},
  'a': {'id': '82', 'title': 'Tottenham', 'short_title': 'TOT'},
  'goals': {'h': '1', 'a': '2'},
  'xG': {'h': '0.361508', 'a': '1.4158'},
  'datetime': '2016-09-24 18:00:00',
  'forecast': {'w': '0.0804', 'd': '0.2526', 'l': '0.667'}},
 {'id': '513',
  'isResult': True,
  'h': {'id': '85', 'title': 'Stoke', 'short_title': 'STO'},
  'a': {'id': '76', 'title': 'West Bromwich Albion', 'short_title': 'WBA'},
  'goals': {'h': '1', 'a': '1'},
  'xG': {'h': '0.979673', 'a': '0.270862'},
  'datetime': '2016-09-24 18:00:00',
  'forecast': {'w': '0.548', 'd': '0.3567', 'l': '0.0953'}},
 {'id': '514',
  'isResult': True,
  'h': {'id': '77', 'title': 'Sunderland', 'short_title': 'SUN'},
  'a': {'id': '78', 'title': 'Crystal Palace', 'short_title': 'CRY'},
  'goals': {'h': '2', 'a': '3'},
  'xG': {'h': '1.51457', 'a': '1.7887'},
  'datetime': '2016-09-24 18:00:00',
  'forecast': {'w': '0.3215', 'd': '0.2471', 'l': '0.4314'}},
 {'id': '516',
  'isResult': True,
  'h': {'id': '87', 'title': 'Liverpool', 'short_title': 'LIV'},
  'a': {'id': '91', 'title': 'Hull', 'short_title': 'HUL'},
  'goals': {'h': '5', 'a': '1'},
  'xG': {'h': '4.64913', 'a': '0.157549'},
  'datetime': '2016-09-24 18:00:00',
  'forecast': {'w': '0.9966', 'd': '0.0031', 'l': '0.0003'}},
 {'id': '517',
  'isResult': True,
  'h': {'id': '73', 'title': 'Bournemouth', 'short_title': 'BOU'},
  'a': {'id': '72', 'title': 'Everton', 'short_title': 'EVE'},
  'goals': {'h': '1', 'a': '0'},
  'xG': {'h': '0.693594', 'a': '1.15724'},
  'datetime': '2016-09-24 18:00:00',
  'forecast': {'w': '0.1971', 'd': '0.3117', 'l': '0.4912'}},
 {'id': '518',
  'isResult': True,
  'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'},
  'a': {'id': '80', 'title': 'Chelsea', 'short_title': 'CHE'},
  'goals': {'h': '3', 'a': '0'},
  'xG': {'h': '1.66224', 'a': '0.613553'},
  'datetime': '2016-09-24 20:30:00',
  'forecast': {'w': '0.6565', 'd': '0.2356', 'l': '0.1079'}},
 {'id': '519',
  'isResult': True,
  'h': {'id': '81', 'title': 'West Ham', 'short_title': 'WHU'},
  'a': {'id': '74', 'title': 'Southampton', 'short_title': 'SOU'},
  'goals': {'h': '0', 'a': '3'},

In [39]:
shot_data = client.match('461').get_shot_data()
shot_data

{'h': [{'id': '112236',
   'minute': '5',
   'result': 'MissedShots',
   'X': '0.9159999847412109',
   'Y': '0.585',
   'xG': '0.016871899366378784',
   'player': 'Curtis Davies',
   'h_a': 'h',
   'player_id': '1686',
   'situation': 'FromCorner',
   'season': '2016',
   'shotType': 'Head',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Robert Snodgrass',
   'lastAction': 'Aerial'},
  {'id': '112242',
   'minute': '29',
   'result': 'MissedShots',
   'X': '0.7580000305175781',
   'Y': '0.18799999237060547',
   'xG': '0.03114919923245907',
   'player': 'Robert Snodgrass',
   'h_a': 'h',
   'player_id': '1691',
   'situation': 'DirectFreekick',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '112243',
   'minute': '33',
   'result': 'MissedShots',
   'X': '0.8390000152587891',
   'Y': '0.3240000152587891',
   'xG': '0.0393792986869812',
   'player': 'Abel Hernández',
   'h_a': 'h',
   'player_id': '1698',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '112247',
   'minute': '41',
   'result': 'MissedShots',
   'X': '0.7480000305175781',
   'Y': '0.3240000152587891',
   'xG': '0.015569999814033508',
   'player': 'Robert Snodgrass',
   'h_a': 'h',
   'player_id': '1691',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Adama Diomande',
   'lastAction': 'Pass'},
  {'id': '112249',
   'minute': '45',
   'result': 'SavedShot',
   'X': '0.9230000305175782',
   'Y': '0.605999984741211',
   'xG': '0.033541399985551834',
   'player': 'Curtis Davies',
   'h_a': 'h',
   'player_id': '1686',
   'situation': 'FromCorner',
   'season': '2016',
   'shotType': 'Head',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Robert Snodgrass',
   'lastAction': 'Cross'},
  {'id': '112250',
   'minute': '45',
   'result': 'MissedShots',
   'X': '0.9730000305175781',
   'Y': '0.44299999237060544',
   'xG': '0.12796500325202942',
   'player': 'Abel Hernández',
   'h_a': 'h',
   'player_id': '1698',
   'situation': 'FromCorner',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '112251',
   'minute': '45',
   'result': 'Goal',
   'X': '0.9719999694824218',
   'Y': '0.43400001525878906',
   'xG': '0.14253799617290497',
   'player': 'Adama Diomande',
   'h_a': 'h',
   'player_id': '1694',
   'situation': 'FromCorner',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Abel Hernández',
   'lastAction': 'Rebound'},
  {'id': '112253',
   'minute': '55',
   'result': 'SavedShot',
   'X': '0.9530000305175781',
   'Y': '0.6619999694824219',
   'xG': '0.06231750175356865',
   'player': 'Abel Hernández',
   'h_a': 'h',
   'player_id': '1698',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '112254',
   'minute': '56',
   'result': 'Goal',
   'X': '0.8619999694824219',
   'Y': '0.48',
   'xG': '0.07905679941177368',
   'player': 'Robert Snodgrass',
   'h_a': 'h',
   'player_id': '1691',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '112255',
   'minute': '59',
   'result': 'BlockedShot',
   'X': '0.7719999694824219',
   'Y': '0.49700000762939456',
   'xG': '0.08592820167541504',
   'player': 'Robert Snodgrass',
   'h_a': 'h',
   'player_id': '1691',
   'situation': 'DirectFreekick',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '112258',
   'minute': '66',
   'result': 'MissedShots',
   'X': '0.700999984741211',
   'Y': '0.5279999923706055',
   'xG': '0.03815549984574318',
   'player': 'Tom Huddlestone',
   'h_a': 'h',
   'player_id': '1695',
   'situation': 'DirectFreekick',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '112263',
   'minute': '81',
   'result': 'SavedShot',
   'X': '0.924000015258789',
   'Y': '0.135',
   'xG': '0.04840020090341568',
   'player': 'Robert Snodgrass',
   'h_a': 'h',
   'player_id': '1691',
   'situation': 'DirectFreekick',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '112264',
   'minute': '84',
   'result': 'BlockedShot',
   'X': '0.775',
   'Y': '0.6819999694824219',
   'xG': '0.021670199930667877',
   'player': 'Adama Diomande',
   'h_a': 'h',
   'player_id': '1694',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Ahmed Elmohamady',
   'lastAction': 'Chipped'},
  {'id': '112265',
   'minute': '91',
   'result': 'MissedShots',
   'X': '0.7069999694824218',
   'Y': '0.45799999237060546',
   'xG': '0.015714799985289574',
   'player': 'David Meyler',
   'h_a': 'h',
   'player_id': '1693',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'}],
 'a': [{'id': '112235',
   'minute': '2',
   'result': 'BlockedShot',
   'X': '0.7290000152587891',
   'Y': '0.6530000305175782',
   'xG': '0.013960099779069424',
   'player': 'Demarai Gray',
   'h_a': 'a',
   'player_id': '762',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'BallRecovery'},
  {'id': '112237',
   'minute': '10',
   'result': 'MissedShots',
   'X': '0.7980000305175782',
   'Y': '0.6969999694824218',
   'xG': '0.020872699096798897',
   'player': 'Demarai Gray',
   'h_a': 'a',
   'player_id': '762',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '112238',
   'minute': '18',
   'result': 'MissedShots',
   'X': '0.915',
   'Y': '0.34',
   'xG': '0.07945209741592407',
   'player': 'Riyad Mahrez',
   'h_a': 'a',
   'player_id': '750',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Jamie Vardy',
   'lastAction': 'Pass'},
  {'id': '112239',
   'minute': '21',
   'result': 'MissedShots',
   'X': '0.765',
   'Y': '0.505',
   'xG': '0.02644439972937107',
   'player': 'Daniel Drinkwater',
   'h_a': 'a',
   'player_id': '752',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '112240',
   'minute': '23',
   'result': 'BlockedShot',
   'X': '0.725',
   'Y': '0.4879999923706055',
   'xG': '0.02020690031349659',
   'player': 'Demarai Gray',
   'h_a': 'a',
   'player_id': '762',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Wes Morgan',
   'lastAction': 'Pass'},
  {'id': '112241',
   'minute': '24',
   'result': 'MissedShots',
   'X': '0.9019999694824219',
   'Y': '0.3240000152587891',
   'xG': '0.06201240047812462',
   'player': 'Daniel Drinkwater',
   'h_a': 'a',
   'player_id': '752',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Riyad Mahrez',
   'lastAction': 'Pass'},
  {'id': '112244',
   'minute': '40',
   'result': 'SavedShot',
   'X': '0.9169999694824219',
   'Y': '0.5670000076293945',
   'xG': '0.4425620138645172',
   'player': 'Christian Fuchs',
   'h_a': 'a',
   'player_id': '749',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Ahmed Musa',
   'lastAction': 'Throughball'},
  {'id': '112245',
   'minute': '40',
   'result': 'BlockedShot',
   'X': '0.919000015258789',
   'Y': '0.4929999923706055',
   'xG': '0.48569199442863464',
   'player': 'Jamie Vardy',
   'h_a': 'a',
   'player_id': '755',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'Rebound'},
  {'id': '112246',
   'minute': '40',
   'result': 'MissedShots',
   'X': '0.8590000152587891',
   'Y': '0.524000015258789',
   'xG': '0.11664500087499619',
   'player': 'Riyad Mahrez',
   'h_a': 'a',
   'player_id': '750',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Ahmed Musa',
   'lastAction': 'TakeOn'},
  {'id': '112248',
   'minute': '42',
   'result': 'MissedShots',
   'X': '0.89',
   'Y': '0.47400001525878904',
   'xG': '0.3912470042705536',
   'player': 'Jamie Vardy',
   'h_a': 'a',
   'player_id': '755',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Ahmed Musa',
   'lastAction': 'Pass'},
  {'id': '112252',
   'minute': '46',
   'result': 'Goal',
   'X': '0.885',
   'Y': '0.5',
   'xG': '0.7611690163612366',
   'player': 'Riyad Mahrez',
   'h_a': 'a',
   'player_id': '750',
   'situation': 'Penalty',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '112256',
   'minute': '60',
   'result': 'MissedShots',
   'X': '0.8180000305175781',
   'Y': '0.61',
   'xG': '0.04028429836034775',
   'player': 'Ahmed Musa',
   'h_a': 'a',
   'player_id': '1681',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'None'},
  {'id': '112257',
   'minute': '61',
   'result': 'MissedShots',
   'X': '0.7519999694824219',
   'Y': '0.2589999961853027',
   'xG': '0.010190299712121487',
   'player': 'Ahmed Musa',
   'h_a': 'a',
   'player_id': '1681',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Daniel Drinkwater',
   'lastAction': 'Chipped'},
  {'id': '112259',
   'minute': '71',
   'result': 'SavedShot',
   'X': '0.7340000152587891',
   'Y': '0.47900001525878905',
   'xG': '0.05383719876408577',
   'player': 'Riyad Mahrez',
   'h_a': 'a',
   'player_id': '750',
   'situation': 'DirectFreekick',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': None,
   'lastAction': 'Standard'},
  {'id': '112260',
   'minute': '72',
   'result': 'BlockedShot',
   'X': '0.9159999847412109',
   'Y': '0.705999984741211',
   'xG': '0.05763629823923111',
   'player': 'Riyad Mahrez',
   'h_a': 'a',
   'player_id': '750',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Jamie Vardy',
   'lastAction': 'LayOff'},
  {'id': '112261',
   'minute': '74',
   'result': 'MissedShots',
   'X': '0.76',
   'Y': '0.53',
   'xG': '0.023916499689221382',
   'player': 'Shinji Okazaki',
   'h_a': 'a',
   'player_id': '754',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'LeftFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Ahmed Musa',
   'lastAction': 'Pass'},
  {'id': '112262',
   'minute': '75',
   'result': 'SavedShot',
   'X': '0.8969999694824219',
   'Y': '0.5690000152587891',
   'xG': '0.03447730094194412',
   'player': 'Shinji Okazaki',
   'h_a': 'a',
   'player_id': '754',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'Head',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Christian Fuchs',
   'lastAction': 'Pass'},
  {'id': '112266',
   'minute': '94',
   'result': 'SavedShot',
   'X': '0.775',
   'Y': '0.5',
   'xG': '0.0306560005992651',
   'player': 'Daniel Drinkwater',
   'h_a': 'a',
   'player_id': '752',
   'situation': 'OpenPlay',
   'season': '2016',
   'shotType': 'RightFoot',
   'match_id': '461',
   'h_team': 'Hull',
   'a_team': 'Leicester',
   'h_goals': '2',
   'a_goals': '1',
   'date': '2016-08-13 15:30:00',
   'player_assisted': 'Daniel Amartey',
   'lastAction': 'Pass'}]}